### ISSUE TITLE
 Test on relayer.testnet.tomochain.com

### ISSUE THREAD

**Issue by intan167** [BuildOnViction/bug-reports#1]
https://relayer.testnet.tomochain.com/ 
can not interact with external wallet, here I use Metamask, OperaCryptoWallet, and TrustWallet. by following the instructions https://docs.tomochain.com/get-started/wallet/ 
￼
![Screenshot_2019-12-19-17-34-24-194_io metamask](https://user-images.githubusercontent.com/54311290/71173953-98aaf180-2296-11ea-88da-8c5429b4be1a.png)
![Screenshot_2019-12-19-17-57-53-085_com wallet crypto trustapp](https://user-images.githubusercontent.com/54311290/71174003-aa8c9480-2296-11ea-963f-e199523e7d14.png)

even using Tomo Wallet though
￼
![Screenshot_2019-12-19-17-59-06-105_com tomochain wallet](https://user-images.githubusercontent.com/54311290/71174036-c001be80-2296-11ea-85e6-d724968a3e07.png)

**Comment by thanhson1085** [comment]
TomoRelayer supports web only, will not support Dapp. Thank you.
