### ISSUE TITLE
Settings And Full View Not Visible in Mobile Dapp

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#10]
I’ve noticed that the settings and full view of chart in the exchange is not visible in the mobile via tomowallet.
![EFC9BE55-C1C9-4DEC-8D08-25BF11B0B6A5](https://user-images.githubusercontent.com/58533399/71616334-bc542d00-2bf0-11ea-83c9-521b74f10604.jpeg)
![08670AF2-FAD3-48D7-B363-216FDBCCA842](https://user-images.githubusercontent.com/58533399/71616335-bc542d00-2bf0-11ea-8d0f-02014c0949be.jpeg)

**Comment by thanhvk** [comment]
Yes, that right the mobile's screen is small so we hide setting and full view buttons of the chart.

**Comment by RonaldDuck** [comment]
You did hide it? Where can we find it? I think you should put it back specially when using landscape mode because most of the traders (my experience) want to see the full view of charts.

**Comment by RonaldDuck** [comment]
I hope i get something from this 😁😁

**Comment by thanhvk** [comment]
> You did hide it?

Yes, I did.

> Where can we find it?

On the mobile, you can't.

> I think you should put it back specially when using landscape mode because most of the traders (my experience) want to see the full view of charts.

Tomo wallet doesn't have landscape mode but we are planning to develop a native version for mobile that gives a better experience. 

Anyway, thank you for your comment. If you have any other ideas, comments welcome.

**Comment by RonaldDuck** [comment]
Will i get something for the recommendation? 😊

**Comment by thanhson1085** [comment]
The team proactively hide the button, so it is a known issue before you create the report.
So you will not get the bounty for this report. Thank you for your contribution. You should contact @Adrian9h via telegram for the details
