### ISSUE TITLE
Plus and Minus Arrows in Mobile

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#100]
Can you also put the plus and minus arrows in the buy and sell page in the Dex via tomowallet? It will be more convenient if you want to add or subtract small amount.
![A93C62BD-7423-490D-AD90-451952327FDA](https://user-images.githubusercontent.com/58533399/73135885-92244c80-4082-11ea-9dab-4ad220aa4fce.jpeg)
![7E0E9D71-AF4E-4C40-BDE0-9309F6B8E8D3](https://user-images.githubusercontent.com/58533399/73135886-93ee1000-4082-11ea-8c19-789db9941af0.jpeg)

**Comment by thanhson1085** [comment]
We do not think we need those buttons. Thank you for the suggestion
