### ISSUE TITLE
Candle indicator not properly seen

### ISSUE THREAD

**Issue by gsarahhhh** [BuildOnViction/bug-reports#101]
Upon browsing I noticed the candle indicator in ETH/TOMO pair which I think is not presented properly unlike other pairs, or is just normal?

![image](https://user-images.githubusercontent.com/59993482/73152625-8df04180-410b-11ea-9bd8-59f716e505e6.png)

**Comment by 0xwhalerush** [comment]
You set time candle 5m - 1h lol

**Comment by thanhson1085** [comment]
It is not an issue.
