### ISSUE TITLE
Scale Properties Countdown 

### ISSUE THREAD

**Issue by gsarahhhh** [BuildOnViction/bug-reports#102]
While changing the scale properties I was curious what will happen when I ticked the countdown

![image](https://user-images.githubusercontent.com/59993482/73154234-a4999700-4111-11ea-8d3d-efaf8224b456.png)

and this happened no countdown is shown after I clicked/ticked the countdown
![image](https://user-images.githubusercontent.com/59993482/73154250-b2e7b300-4111-11ea-80ba-7778aa6a045d.png)

Sometimes it will appear
![image](https://user-images.githubusercontent.com/59993482/73154543-8d0ede00-4112-11ea-8984-fb42e9ebda83.png)

but after I switched to light mode the countdown will disappear
![image](https://user-images.githubusercontent.com/59993482/73154583-b596d800-4112-11ea-8663-5d917bfb9802.png)

**Comment by thanhson1085** [comment]
We have to re-select countdown option. It is too minor to be considered as an issue.
