### ISSUE TITLE
Help Center/Contact Us Tab

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#103]
Hello. Can i suggest something? So i've been testing the platform for quite some time now, and i have some few questions regarding on my account and trading. I feel like i need to talk to someone with those questions. Can you also put a Help Center/Contact Us tab? You can put the tab on the red circle in the photo.
![tomo](https://user-images.githubusercontent.com/58533399/73181170-abe09500-4151-11ea-966d-8ea9b0d7f793.png)

**Comment by thanhson1085** [comment]
We have support button on right top, we will not consider this suggestion.
