### ISSUE TITLE
404 Not found detail tomo on relayer

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#105]
![IMG_20200128_030005](https://user-images.githubusercontent.com/59077947/73209262-80be6b80-417a-11ea-8414-6757f9ccafc9.jpg)
![Screenshot_2020-01-28-02-58-54-36](https://user-images.githubusercontent.com/59077947/73209265-81570200-417a-11ea-9aa4-91da87c4a803.png)

**Comment by thanhson1085** [comment]
TOMO is a native token, there is no url for TOMO.
It is too minor to be considered it as an issue.

**Comment by WhaleCMD** [comment]
Token info no found
#166

**Comment by 0xwhalerush** [comment]
this case is the same as #166  will you get 2 prizes

**Comment by 0xwhalerush** [comment]
#105 in the info token and #166  bug section in the search section

**Comment by thanhson1085** [comment]
It is not same.
link to scan.testnet.tomochain.com is correct

**Comment by WhaleCMD** [comment]
You can bro

**Comment by 0xwhalerush** [comment]
You can check bro
