### ISSUE TITLE
Relayer Profile page crash in case of wallet's zero balance

### ISSUE THREAD

**Issue by UmckaBear** [BuildOnViction/bug-reports#106]
These are two bugs connected with each other.

**A.** Relayer profile page can't correctly show zero balance. It shows empty fields. Balance and Owner profile wallet you will see after 1 min on server response. No issues with even 1 TOMO on balance

![ZeroBalance](https://user-images.githubusercontent.com/31537952/73217855-688e2280-4161-11ea-841a-8c0596555026.jpg)

**B.** When you open Relayer profile on Transactions tab, using wallet with zero balance, page will crash after server response.

How to reproduce.
1. Login to Relayer with using zero TOMO balance wallet
2. Click Profile.
3. Click "Balance" -> "Transactions"
4. Wait 1 min (until received server's response)

![RelayProfileZeroBalance](https://user-images.githubusercontent.com/31537952/73216287-637ba400-415e-11ea-9db6-802a2c0a1a08.jpg)

You can check video below:
https://drive.google.com/file/d/1xUy6t3MaWwl_8PBWBT1pP1EjeH-OR7QT/view?usp=sharing

You should receive 0 TOMO balance in profile without idles, same as normal balance. Zero balance should not affect page crash.

**Comment by 0xwhalerush** [comment]
Same my issue blank
https://github.com/tomochain/bug-reports/issues/30

**Comment by UmckaBear** [comment]
@WhaleCMD Not the same, since you use wallets with balance. Issue connected with zero balance and occurs in Profile section. Nothing connected with deposit operations. Also it can be easily reproduced.

**Comment by thanhson1085** [comment]
That request calls TomoScan APIs that is not in scope of program.
