### ISSUE TITLE
Hidden Mnemonic Phrase (Can't check if there are errors)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#108]
Hello. I noticed something when trying to open my wallet on relayer using Mnemonic phrase. Is it really hidden? Or there are no other ways to unhide it? This becomes an issue when i misspelled one word on my phrase, so ill delete it all and again start to type again.
![reveal](https://user-images.githubusercontent.com/46350890/73370824-c6e90b80-42ef-11ea-8ac9-49206e283d7f.png)

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
Hide the keys is OK, we do not consider it as an issue.
