### ISSUE TITLE
Different Address Showing up when trying to open wallet Using private key and mnemonic phrase

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#109]
Hello.
I tried to open wallet using private key and mnemonic phrase. I have a tomo balance of 40650.93...  At first, i tried to open it using my private key, from the video, you can see the private key and mnemonic phrase of my wallet which i have already typed in my ms word. As i tried to paste the private key and click Unlock, it shows proper balance and proper address just like in this picture:
![pkey](https://user-images.githubusercontent.com/46350890/73372528-598aaa00-42f2-11ea-9702-e02b99f36744.png)
I tried now to open using mnemonic phrase, i copied and paste my mnemonic phrase but as i click unlock it shows a different wallet and a 0 tomo balance like this:
![mne p](https://user-images.githubusercontent.com/46350890/73372586-732bf180-42f2-11ea-89ed-402b6d9f4290.png)

Is this normal? I am willing to submit myself to any reproduction of this issue and i hope you can give me a safer way to prove that the mnemonic phrase and private key of my tomo wallet is one account. 

Any ways, i also made a video of my encounter here (I have covered some part of the keys and phrase for privacy but im willing to submit the key and phrase to an authorized tomochain dev for checking since its balance is purely testnet tokens:
https://youtu.be/h4RwtfOuNoo

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
It is not an issue. With mnemonic phrase, you have to know what is your hd path.

**Comment by CryptoChaser13** [comment]
So a different address will show when using mnemonic phrase , also with using private key?
