### ISSUE TITLE
Bug on Relayer Deposit

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#110]
Hello. I tried to deposit in my relayer under Configurations Tab. As i deposit some tomo, the amount which i deposited are just being indicated on remaining deposit number by number, i think it doesn't perform any mathematical operation such as substraction; that the amount which i deposited must be deducted on remaining deposit. You can see the video below:
![depo](https://user-images.githubusercontent.com/46350890/73376535-8b9f0a80-42f8-11ea-8095-2211786e7841.png)

https://youtu.be/V9LUFf1kBac

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by UmckaBear** [comment]
This bug already known by developers
https://github.com/tomochain/tomorelayer/issues/75

**Comment by CryptoChaser13** [comment]
Thanks @UmckaBear

**Comment by thanhson1085** [comment]
Thanks @UmckaBear, duplicated https://github.com/tomochain/tomorelayer/issues/75
