### ISSUE TITLE
Name Change don't match

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#111]
Hello. I tried to change my relayer name from "TOMOMIRA" to "Tomochain Mira" but as you can see, the name changed already on my dashboard but not yet on my "My Relayers" button:

![rel](https://user-images.githubusercontent.com/46350890/73406719-12bca480-4332-11ea-9a62-d578c1a2de33.png)

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
Yep, the name on the menu will be updated if you logout and login again.
It is too minor to be consider it as an issue.
