### ISSUE TITLE
Relayer deducts balance on total amount even when the amount is not in available amount (in open order)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#112]
Hello. I noticed something when trying to deposit to my relayer page. 

At first, i have submitted a buy order on dex where my current fund is 637.929281055009381752 TOMO. I submitted a 100% buy order on dex with very small price rather than those in orderbook. So now my order is successfully submitted and i only have some decimals left in my avialable amount.

Now, i turned to my relayer page with same account (same address) and tried to make a deposit. You can also see my balance of  637.929281055009381752  at the current balance. So i tried to deposit about 637 tomo to my relayer page. Unexpectedly, the deposit was successful and the amount was deducted to my total balance at dex even if i have a balance in order.

I expect tomo relayer must indicate also (at deposit section) the available amount in my wallet to be deposited and must not deduct if available balance dont meet my deposit amount.

Please check the video here which can elaborate further:
https://youtu.be/xIwW-zMNg68

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
TomoX does NOT lock "in order" balance, so you can send the balance to the other address. it is normal.
