### ISSUE TITLE
Shutdown Relayer Not Working

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#114]
Hello. I tried to shut down my relayer. It's not functioning however. Please check the video here:
https://youtu.be/gSzKVybds3Y

**Comment by thanhson1085** [comment]
Shutdown Relayer works, but it does not show the refund screen that i created the issue here: https://github.com/tomochain/tomorelayer/issues/78

**Comment by CryptoChaser13** [comment]
Its a bug right sir? On the video that i made, it says Unable to Resign

**Comment by thanhson1085** [comment]
In the video, you shutdown your relayer after the first click. In the second click, you can not shutdown it again, because your relayer already shutdown.

**Comment by CryptoChaser13** [comment]
If it has shutdown on first click, why can i still access my relayer?

**Comment by thanhson1085** [comment]
You can access it to get the refund after 30days, but you can not trade or transfer your relayer.
