### ISSUE TITLE
Can't Transfer Relayer on New Owner

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#115]
Hello. I tried to transfer my relayer owner to my metamask account. I have pasted the metamask address and a new coinbase address but it's unable to transfer. Is this normal?

https://www.youtube.com/watch?v=oJRw64IB__4&t=39s

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/tomorelayer/issues/77
