### ISSUE TITLE
Blank pages on some buttons on relayer

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#117]
Hello. When i tried to click on different buttons encircled on the picture below, it shows blank pages, This includes "Need helps?", "Privacy Policy", "Term of Services" and "API Documents"

![blank](https://user-images.githubusercontent.com/46350890/73533706-69250280-445a-11ea-8394-da8acd32aefe.png)

**Comment by CryptoChaser13** [comment]
I would also like to add "Help" button on upper right which has also blank page
![help](https://user-images.githubusercontent.com/46350890/73534372-ec932380-445b-11ea-9dce-130e8fb43c94.png)

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/tomorelayer/issues/74
