### ISSUE TITLE
"Need Help?" instead of "Need helps?'

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#118]
Hello. Im referring to a grammatical n=bug which is the "Need helps?' button below. I expect this must be "Need Help?" or "Need a Help?" instead of "Need helps?" which is an improper phrase. 
![need helps](https://user-images.githubusercontent.com/46350890/73534115-50691c80-445b-11ea-9d7d-36724120a001.png)

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/tomorelayer/issues/74

**Comment by thanhson1085** [comment]
I think "need help" and "need helps" both are OK. It also is too minor to be consider as an issue.

**Comment by CryptoChaser13** [comment]
Isn't this a misspelled bug?

**Comment by thanhson1085** [comment]
Yep, I am not English person. But i checked it in google and google translate: https://www.google.com/search?q=%22need+helps%22&rlz=1C1CHBF_enVN816VN816&oq=%22need+helps%22&aqs=chrome..69i57j0l7.6646j1j7&sourceid=chrome&ie=UTF-8
