### ISSUE TITLE
Negative words left, Can type unlimited characters

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#119]
Hello. I tried to make a new relayer and under the "Type your relayer name" , i noticed that the "200 words left" have no much sense since you can still type more characters on the box and the number continues to lessen even at negative words left (-25 words left as you can see below)
![-25](https://user-images.githubusercontent.com/46350890/73536013-ebfc8c00-445f-11ea-97cb-344d1b665fd3.png)

**Comment by UmckaBear** [comment]
You can type but you can't apply this name due correct checking. For example, in Twitter you can see same limitations, when you enter more then can characters. Same for name change for already created relayer. It will not allow to change name more then 200 characters. I think there no issues.

**Comment by CryptoChaser13** [comment]
Thank you for your feedback. But for me, Well i think this is a more formal case than twitter cause its a relayer exchange platform. And an issue to someone can not be an issue of the other if he will just disregard it, yet others still take regards

**Comment by CryptoChaser13** [comment]
Misclicked close and comment button.

**Comment by thanhson1085** [comment]
Yep, it is too minor to be consider it as an issue.
