### ISSUE TITLE
Not change on decimals on volume and amount cause overlap

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#121]
Seems like when i change the decimals numbers only the price change not on the amount
 and volume so there is an overlap on the amount and volume the decimals should on the smallest default not on 7 decimals as a default.

![decimals](https://user-images.githubusercontent.com/38444647/73592545-9fd04b00-4536-11ea-8b8b-c041af7aa4af.jpg)

**Comment by thanhvk** [comment]
Decimals only for the price not for amount, volume and this is duplicated with https://github.com/tomochain/bug-reports/issues/24
