### ISSUE TITLE
Market "Search" button only works for 1st word search but can't search for 2nd word

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#123]
Hello. I may not have provided the best title for this issue. But, i tried to search a pair on the market, i input "tomo" on search button but it only shows "No pair found". This could be equivalent to "There is no pair for Tomo" right? I expect once i searched at least a keyword of a pair even if the coin is at second place of a pair, it must be found in search button. For example if i search btc, it would only show BTC/TOMo, but it doesn't show ETH/BTC and XRP/BTC. 

![tomo](https://user-images.githubusercontent.com/46350890/73604008-60047480-45c5-11ea-9b9a-de9d7dee112f.png)
![tomo1](https://user-images.githubusercontent.com/46350890/73604096-4152ad80-45c6-11ea-9be5-8b0989f61b81.png)

**Comment by CryptoChaser13** [comment]
To add, it must look like this where if i search tomo, all tomo pairs can be found:

![tomoo](https://user-images.githubusercontent.com/46350890/73604033-c12c4800-45c5-11ea-8b2e-7e3406927636.png)

**Comment by CryptoChaser13** [comment]
The same with BTC:

![tomooo](https://user-images.githubusercontent.com/46350890/73604079-1c5e3a80-45c6-11ea-9865-5d0b41135bc8.png)

**Comment by thanhvk** [comment]
I was thinking about this before when I implemented a new search function in here:

![](https://user-images.githubusercontent.com/46350890/73604033-c12c4800-45c5-11ea-8b2e-7e3406927636.png)

and I think the current search function still good for the markets page.

Maybe we will implement a new search function on the markets page if there are more requests in the feature.

Thanks.

**Comment by CryptoChaser13** [comment]
Thank you sir @thanhvk 

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhvk** [comment]
@MirasolFerrer sorry but you do not get the reward for this issue because we do not implement your proposal now, and we will wait for more requests as I said.

**Comment by CryptoChaser13** [comment]
Ill just input my wallet in case you made your decisions sir. Because if a new user will go on market and will search for pairs but can't see any pair, they will wurely become unfamiliar.

**Comment by thanhson1085** [comment]
In market page, you only search keyword for base tokens, not for quote tokens.
We do not consider it as an issue.

**Comment by CryptoChaser13** [comment]
Its labelled as enhancement sir @thanhson1085

**Comment by thanhson1085** [comment]
Yep, but we will not implement it at least in this phase.
