### ISSUE TITLE
Orange Line Disappear in Docs/FAQ

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#124]
I saw something in the tabs. When i place the cursor in markets, exchange and portfolio, there’s an orange line beside it, but i does not show in docs/FAQ tab. Also when i click the exchange tab, the orange line disappears in every tab. Is this a bug?
![D54327DC-C4CD-4185-BD8C-61B6561ED80A](https://user-images.githubusercontent.com/58533399/73607928-82af8100-45f7-11ea-9c4e-6d6dde460527.jpeg)
![FA4EBCD4-5645-4EB7-A3BD-3D28063E8B3F](https://user-images.githubusercontent.com/58533399/73607929-83481780-45f7-11ea-9817-cda494e2534b.jpeg)
![4980112D-367E-4440-B560-EBF177C105E2](https://user-images.githubusercontent.com/58533399/73607930-83e0ae00-45f7-11ea-81dd-fcf276db02ab.jpeg)

**Comment by thanhson1085** [comment]
It links to external site, we do not need high light on hover.
