### ISSUE TITLE
Translucent Window When Clicking Buy or Sell in Light Mode Using Brave Browser

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#125]
When i'm making an order, there's a translucent window appearing whenever i click the buy or sell button in light mode. It does not appear in dark mode though. I'm using the latest version of Brave Browser.
![tomo](https://user-images.githubusercontent.com/58533399/73608493-90b4d000-45fe-11ea-89e5-82b5289a608c.png)

**Comment by thanhson1085** [comment]
It loaded forever?, or you just report about color of loading screen?

**Comment by RonaldDuck** [comment]
When it loads, the color of the screen appears. It does not show on chrome browser

**Comment by thanhson1085** [comment]
Got it. But it it too minor to be considered as an issue in this phase. Thank you.
