### ISSUE TITLE
"Uncaught (in promise) Invariant Violation"

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#128]
I tried to apply a logo to my relayer. As i pasted the link of the photo, the page became blank and as i checked on console, It shows "Uncaught (in promise) Invariant Violation" with a red colored font. I also clicked the link it provided and it shown me: Objects are not valid as a React child (found: object with keys {code, message, detail}). Is this normal?

The image link i pasted is tomochain picture.

![ERROR LOGO](https://user-images.githubusercontent.com/46350890/73738295-368f4880-477f-11ea-906d-31901b40f380.png)

![error two](https://user-images.githubusercontent.com/46350890/73738318-3ee78380-477f-11ea-80bb-2dae4d0100cb.png)

**Comment by thanhson1085** [comment]
It is not normal, what link did you use? did you resign your relayer? How to reproduce it?

**Comment by CryptoChaser13** [comment]
I did not resign my relayer. But i copied the link address of any image in google (selecing tomochain logo), pasted it to the relayer photo url, submitted it and got the blank screen. Upon clicking Inspect Element, i have got the errors. 


My expectation is that, if the photo link isn't allowed, it must pop-up a "Invalid Photo Url" rather than a blank screen which make me reload the relayer and reopen again.

**Comment by CryptoChaser13** [comment]
This is a follow-upof the issue i encountered. I tried using a different photo today, which is the link used in the page itself. You can watch the error here which supports my encounter:

https://youtu.be/2MS8jissxGs

**Comment by thanhson1085** [comment]
You input wrong image url, the url have to start with 'http' or 'https'.
TomoRelayer do not validate the inputs, we created the issue here. https://github.com/tomochain/tomorelayer/issues/73

**Comment by CryptoChaser13** [comment]
Sir. I think i have included that in my expectation here:
https://github.com/tomochain/bug-reports/issues/128#issuecomment-583788353

My expectation is that, if the photo link isn't allowed, it must pop-up a "Invalid Photo Url" rather than a blank screen which make me reload the relayer and reopen again.

That should have cleared the issue which Relayer must do a validation.

**Comment by thanhson1085** [comment]
If there is validation, you can not submit a wrong link. Then you will not meed the blank page.

**Comment by CryptoChaser13** [comment]
And that's what i expect instead of a blank page , at least "Invalid Photo Url" or "Link not Allowed"

**Comment by thanhson1085** [comment]
I understand. So it is duplicated issue https://github.com/tomochain/tomorelayer/issues/73

**Comment by CryptoChaser13** [comment]
Okay. Thanks @thanhson1085
