### ISSUE TITLE
Add Features "market and Stop-limit"

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#13]
Hi guys, it is possible to add this trading features the market and stop-limit?
we all know that stop-limit has a great feature to mitigate risk.

thank you.
![stoplimit](https://user-images.githubusercontent.com/38444647/71651763-17099800-2d5b-11ea-9eec-3211fd58e65d.png)

**Comment by thanhson1085** [comment]
Yep, known suggestion, we added the market: https://github.com/tomochain/tomox-sdk-ui/issues/97
No plan to add Stop-limit for decentralized exchange.
