### ISSUE TITLE
Indicator not moving when clicked on "Feedback"

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#131]
Hello. On my relayer page, I have clicked first on the Configuration. Suddenly, as i clicked on the Feedback, the violet indicator below Configuration isn't moving. You can see it in this picture:

![violet](https://user-images.githubusercontent.com/46350890/73745560-45312c00-478e-11ea-9c48-8cad6e049677.png)

**Comment by thanhson1085** [comment]
It is too minor to be considered as an bug.
