### ISSUE TITLE
Some errors today in relayer

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#132]
Hello. I tried to load the relayer today at about 7:00 am Philippine Standard Time and got some issues GET https://relayer.testnet.tomochain.com/api/public net::ERR_CONNECTION_CLOSED and the page is just loading and cant be reached.

Here is the video of my encounter:
https://youtu.be/EHIaIujXOrE

**Comment by thanhson1085** [comment]
Thank you for the information.
The site works now. We do not sure what happen that time.
