### ISSUE TITLE
Tried to Attack Relayer Site

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#133]
Hello. I am actually hesitant if i should post this one here. But if its considered an issue, it should have been posted here.

I tried to do an attack with the relayer site. I used Switchblade version 4.0 with this one. I am actually just making an attempt at first and im hesitant that this wont work. But as you can see on the video below, As i start the attack, the page become unresponsive and relayer site cannot be reached (You can also see the errors at the Console) . I even tried to reload the page several times and still an't be reached. So now i tried to stop the attack, then the site is up again and can be reloaded now. 

I would be glad if this becomes an issue at your side. 

Here is the video of my encounter:
https://youtu.be/-urpuI6a5nw

**Comment by CryptoChaser13** [comment]
I tried to make an attack again now at 10:55 pm Philippine Standard time and the site can't be reached/still errors came, Is this somewhat a ddos attack?:

![20200206_225532](https://user-images.githubusercontent.com/46350890/73948457-dfd45c80-48ad-11ea-9b2e-d0799a66824d.jpg)

**Comment by thanhson1085** [comment]
Thank you for information. But DDOS is out of the scope of the program

**Comment by CryptoChaser13** [comment]
Okay sir @thanhson1085 :)
