### ISSUE TITLE
Attack on Dex site 02/06/2020 at 10:15 pm Philippine Standard Time (Received errors)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#134]
Hello. I tried to do a simple attack on the dex site using again Switchblade version 4.0. As you can see on the video and picture ill be attaching here, i received lots of errors in console. I double check this error when loading the dex on the dapp itself and i also got the errors which you can found on the separate video below. Ill be glade to share it if this is an issue somewhat a Denial of Service.

![error](https://user-images.githubusercontent.com/46350890/73945595-8280ef80-492f-11ea-9ece-41009204b967.png)

https://youtu.be/lvSRhgOY9lU

**Comment by CryptoChaser13** [comment]
Here is the dapp dex encounter:

https://youtu.be/gEgyQrHf4Jo

**Comment by CryptoChaser13** [comment]
![20200206_225917](https://user-images.githubusercontent.com/46350890/73948748-3cd01280-48ae-11ea-8af3-580ebafed376.jpg)

**Comment by thanhson1085** [comment]
Thank you for information. But DDOS is out of the scope of the program

**Comment by CryptoChaser13** [comment]
Really sir @thanhson1085 ? Okay. Thank you sir.
