### ISSUE TITLE
No spacing between "derivation" and "Path"

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#135]
Hello, Here is a spacing bug which i just seen now: No spacing between "derivation" and "Path" 
![Spacing](https://user-images.githubusercontent.com/46350890/74025702-7d7b7900-49df-11ea-86d5-507ec07e1743.png)

**Comment by 0xwhalerush** [comment]
Lol

**Comment by CryptoChaser13** [comment]
Yes @WhaleCMD ? Any problem? You did not figure it out?

**Comment by thanhson1085** [comment]
It is too minor to be considered it as an bug. Thank you.

**Comment by CryptoChaser13** [comment]
Its okay sir. Thanks @thanhson1085
