### ISSUE TITLE
Can't open Metamask Wallet on Relayer today Feb. 09, 2020 9:20 pm. Philippine Standard Time

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#137]
Hello. It seems i cannot open my metamask wallet on relayer today Feb. 09, 2020 9:20 pm. Philippine Standard Time. Errors are shown at the right side. It seems https://rpc.testnet.tomochain.com/ is down. I have also tried it on mozilla firefox browser on video shown below.

![rpc](https://user-images.githubusercontent.com/46350890/74102951-08e13f80-4b83-11ea-90d1-3bf728f1a030.png)
![rpc2](https://user-images.githubusercontent.com/46350890/74102954-0c74c680-4b83-11ea-96fe-2f0eb0ec62e7.png)

Video Proof:
https://youtu.be/zFcMYCGxFlw

**Comment by thanhson1085** [comment]
Testnet is down that time
