### ISSUE TITLE
Error in Websocket when change proxy access at firefox in accessing the dex (Sometimes loaded/ Sometimes Lost)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#138]
Hello. I tried to use a different proxy using Manual Proxy Configuration; HTTP PROXY: localhost PORT: 8080 and installed necessary certificate. Now i tried to gain access to the dex and relayer. But ill just submit report here for the dex. It shows the picture below:

![normal](https://user-images.githubusercontent.com/46350890/74151641-8ff7eb80-4c47-11ea-9a39-37ddb174a7fe.png)

May i ask if this is normal? Cause it shows also: error { target: WebSocket, isTrusted: true

**Comment by thanhson1085** [comment]
It is normal, If the client lost connection with the server, it will try to reconnect and show the error log.
