### ISSUE TITLE
Can't see Available assets/Locked Assets on Buy and Sell Page. 

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#14]
I would like to suggest this feature, and this is also based on my experience as a manual trader:
Available Assets and Locked Assets must be indicated above the buy and sell button. I cannot see available assets or locked assets when i start a trade in Buy and Sell page. It might not be a major concern for traders but for sure if someone wants to buy or sell a specific number of asset, they can not only choose 25%, 50% , 75% or 100% of their asset, but specific part of it if they can see their available assets. Another concern would be this could be helpful for manual traders because once their first order is successully filled, their assets will be transferred immediately to the pair they selected, they can easily execute new order especially in manual trading. I hope this could help as a suggestion for Tomochain. 
![20200102_125505](https://user-images.githubusercontent.com/46350890/71652308-4d9ece80-2cd9-11ea-9019-2d0e854688be.jpg)

**Comment by zillabytes** [comment]
this is working fine to me. just hit the 25% or anything on percentage then it will show you the amount. but I want to request if when click the btc the amount show must be clickable and automatically put on the data field.

**Comment by CryptoChaser13** [comment]
Hello @zillabytes that is not what im referring, what im referring to is the available balance that you can see either below or above the buy or sell button, where manual traders can see immediately once their trade is completed if their balance is transferred to the pair they selected. Here are samples from several existing exchange of what im referring, the Available Assets and even Locked Assets:

![20200102_180124](https://user-images.githubusercontent.com/46350890/71661765-1c87c380-2d04-11ea-9978-12bfd3b40baf.jpg)
![20200102_180137](https://user-images.githubusercontent.com/46350890/71661771-227da480-2d04-11ea-88b0-a7e4c87639fb.jpg)

**Comment by thanhson1085** [comment]
This is a known suggestion. 
https://github.com/tomochain/tomox-sdk-ui/issues/186
https://github.com/tomochain/tomox-sdk-ui/issues/154

**Comment by CryptoChaser13** [comment]
I cannot see this one one mobile dapp:
![20200103_141107](https://user-images.githubusercontent.com/46350890/71709571-d470ab80-2dac-11ea-87c9-3299bd773ef9.png)

**Comment by thanhson1085** [comment]
Not released yet. Will release it in the next version.

**Comment by CryptoChaser13** [comment]
I wont get any reward sir?

**Comment by thanhson1085** [comment]
Yep, we created a duplicated issue that was created or solved by the team.

**Comment by CryptoChaser13** [comment]
I hope i get at least little reward???
