### ISSUE TITLE
Future To-Do Tasks

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#140]
Hello, may i just ask if there will be future confirmed bugs and enhancement from Phase 1 that will be added , and resolved in To-Do?

**Comment by thanhson1085** [comment]
We closed the project board, we will not use it any more.

You can filter label "resolved" to know what issue was resolved

**Comment by CryptoChaser13** [comment]
So these remaining unresolved will forever stay as bugs sir?

**Comment by thanhson1085** [comment]
No, we will plan to fixed it internally, and let you know it is resolved or not in the next release.
Take a look the same question https://github.com/tomochain/bug-reports/issues/139

**Comment by CryptoChaser13** [comment]
Thank you sir @thanhson1085
