### ISSUE TITLE
Can't Input price on Market Trade 

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#142]
I think the added Market Trade is still unaccessible. The price is with fixed characters of "Market" so i cannot type any price there. 
![Market](https://user-images.githubusercontent.com/46350890/75094453-3b009180-55c6-11ea-8d9f-074c73601924.png)

**Comment by thanhson1085** [comment]
Market order means you want to BUY/SELL the asset with any price. That why you do not need to input the price.
