### ISSUE TITLE
Bounty for “enhancement” issue

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#143]
You said that the phase 2 bounty is for bugs only. But my issue #91 that has been labeled as “enhancement” got rewarded. Why is that?

**Comment by thanhson1085** [comment]
No Reward.
You added the label, not us.

![Annotation 2020-02-24 102142](https://user-images.githubusercontent.com/546540/75127058-86fb2580-56ef-11ea-8ac9-fc8c7d7e1f46.png)

The label does not decide you have reward or not. We will commented to confirm to the issue that has reward.

**Comment by RonaldDuck** [comment]
This is not the issue i’m talking about, it was issue #91. And i did not put the label, @thanhvk did with low severity, it was also rewarded. You said also that the issue was to help for enhancement in the telegram group.

**Comment by thanhson1085** [comment]
Is it "phase 1" issue?

**Comment by thanhson1085** [comment]
It had a mistake my team. I did not confirm that issue.
