### ISSUE TITLE
#26 Issue Not Rewarded

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#145]
I've seen that the issue #26 has been resolved in the dex but it has not been rewarded, it is phase 1 issue.

**Comment by thanhson1085** [comment]
Seems that. @thanhvk can we mark it as resolved?

@RonaldDuck in this case, you can comment to the issue. Do not need to create a "question" issue.

**Comment by RonaldDuck** [comment]
@thanhson1085 okay sir. I will next time, thank you!

**Comment by thanhvk** [comment]
@thanhson1085 , @RonaldDuck  yes, issue #26 resolved.
