### ISSUE TITLE
No Label For Trade History

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#146]
I've noticed that you've included a traded history window beside the orderbook, but i think you forgot to include the "Trade History" label. Might be confusing if there's no label with that window.
![tomooo](https://user-images.githubusercontent.com/58533399/75305905-631c1900-5882-11ea-927e-6536b037d651.png)

**Comment by thanhson1085** [comment]
I do not think we need add label "Trade History" there
