### ISSUE TITLE
Bug on Autofill of Pass

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#147]
Hello. I noticed a bug  on the password autofill. As i save and autofill a pass using mnemonic or private key and reload the site, the username which is the private key is being typed automatically on the "Total:' box which i encircled on the photo below. I think this isn't normal because the autofill data redirects to a particular part of the dex, which in this case is the "Total:" box. 

Here are the steps to reproduce:

1. Open https://dex.testnet.tomochain.com

2. Unlock wallet either using mnemonic or private key, tin my case, private key

3. Save password on pop-up to enable autofill

4. Reload the dex and point cursor on box above Unlock Wallet. You can see that the username (which this time is the private key numbers are automatically displayed on "Total:" box below "Sell" category.

You can see the photos here:

![autosave](https://user-images.githubusercontent.com/46350890/75310371-c6ac4380-588e-11ea-9586-87ffef0554cf.png)
![Market](https://user-images.githubusercontent.com/46350890/75310613-6964c200-588f-11ea-9bbd-c6697af1232d.png)
![2](https://user-images.githubusercontent.com/46350890/75310619-6ec20c80-588f-11ea-8199-17a306f8516b.png)

These photos are captured both in google chrome browser and brave browser.

**Comment by thanhvk** [comment]
This is duplicate with https://github.com/tomochain/tomox-sdk-ui/issues/209

**Comment by CryptoChaser13** [comment]
Hello sir @thanhvk May i ask how is it duplicated? I think the auto-fill is a browser function and which is a fixed function in browsers like google and brave. How aboutt those who just want to use auto-fill either to lessen activity or if they got ping for a while?

**Comment by thanhvk** [comment]
Hi, @MirasolFerrer  we plan to disable this feature because have some risks. The details in here https://github.com/tomochain/bug-reports/issues/57

**Comment by CryptoChaser13** [comment]
Hello sir, in addition @thanhvk i think the picture below describes the issue where you dedicated a duplication : https://github.com/tomochain/tomox-sdk-ui/issues/209

![2](https://user-images.githubusercontent.com/46350890/75312246-4ab4fa00-5894-11ea-8efe-64312bfb0a65.png)

It is where i see is solved already because as i click on the boxes, there is no autosave. The autofill im telling is when i reload the dex accompanied by the steps i have included.

**Comment by CryptoChaser13** [comment]
My issue also is not only including private key pass but also mnemonic phrase where i can put any character in username on autofill

**Comment by thanhvk** [comment]
>My issue also is not only including private key pass but also mnemonic phrase where i can put any character in username on autofill

https://github.com/tomochain/tomox-sdk-ui/issues/209 also for the mnemonic phrase and other issues related to the auto-fill feature like when users click on the search box or session password, ... 

If you look issue https://github.com/tomochain/tomox-sdk-ui/issues/209 you can see have a commit about mnemonic before you post this issue.

We will add more detail to our issues to avoid misunderstanding.

**Comment by CryptoChaser13** [comment]
Thanks therefore sir.
