### ISSUE TITLE
Add option for Daytime/Dark Mode Display

### ISSUE THREAD

**Issue by AlyRam18** [BuildOnViction/bug-reports#15]
Can i suggest a Daytime/Darkmode Display on the Decentralized Exchange? My friends who are also traders have been suggesting this to any decentralized exchange especially that we are 
having hard time in a dark background. Hope there is a button there that we can just click whenever we cant to change background. 
![20200103_143111](https://user-images.githubusercontent.com/59430599/71710160-d92d7200-2e35-11ea-9fe8-05f8224aa6b1.jpg)

**Comment by AlyRam18** [comment]
And is you suggeset we must add up the brightness in our mobile phone will just make one's eye uncomfortable. Just a simple suggestion to have a display option both daytime and dark mode

**Comment by thanhson1085** [comment]
Thank you for the suggestion. But we have no plan to implement this suggestion in this phase

**Comment by MirasolFerrer** [comment]
Oh its still a public user issue. Like on other exchange.

**Comment by AlyRam18** [comment]
@thanhson1085 This is what we always suggest on other exchanges too

**Comment by thanhson1085** [comment]
We have to prioritize the works. We can not add all features to the apps at the same time.
