### ISSUE TITLE
Bug resolved as per checking

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#150]
Hello sir @thanhson1085 @thanhvk 
seems this issue is solved already as i checked all pairs:

 https://github.com/tomochain/bug-reports/issues/29

**Comment by thanhvk** [comment]
Hi @MirasolFerrer,

I'm not sure about that, in the issue https://github.com/tomochain/tomox-sdk-ui/issues/204 I'm only format price with corresponding precision and it seems the issue #29 not happen. I think we need more time to make sure it not happen.

**Comment by CryptoChaser13** [comment]
I provided all required details even screenshot to reproduce my issue. And its already confirmed as a bug.

**Comment by thanhson1085** [comment]
Commented in the issue
