### ISSUE TITLE
Invalid Button Name

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#152]
Hello. I just found out this button name when i tried to point my cursor on chart settings, This shows what i encircled on the photo below. Is this normal? Or should it display "Chart Settings" instead?

![paint](https://user-images.githubusercontent.com/46350890/75752737-44c38b00-5d64-11ea-9d31-5ba7e2aa8bc6.png)

**Comment by thanhson1085** [comment]
Those are token addresses. We do not consider it as an issue.
