### ISSUE TITLE
Vietnam Language Not Working

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#155]
I've noticed that the turkish language has already been working from the import wallet page to exchange page. but the Vietnam language is still not working, even in a single page.
![tomo](https://user-images.githubusercontent.com/58533399/75811894-36a75600-5dc8-11ea-91b4-4e3101315c6f.png)
![tomo1](https://user-images.githubusercontent.com/58533399/75811910-3c9d3700-5dc8-11ea-802e-368afa4f4f12.png)

**Comment by thanhvk** [comment]
Hi, @RonaldDuck

This is not a bug, Viet Nam language still in progress.
