### ISSUE TITLE
Graphic Bug In Import Wallet Page

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#156]
I've encountered an unusual graphic bug in Import Wallet page. To reproduce, go to the import wallet page, without importing your wallet, click the exchange. In the exchange page, click the back button to take you back to the import wallet page.
![tomo1](https://user-images.githubusercontent.com/58533399/75812752-b7b31d00-5dc9-11ea-9308-8c0215426ada.png)
![tomo](https://user-images.githubusercontent.com/58533399/75812729-ae29b500-5dc9-11ea-9f2c-57d7a88f0d91.png)

**Comment by thanhvk** [comment]
This is duplicate with https://github.com/tomochain/tomox-sdk-ui/issues/229

**Comment by thanhson1085** [comment]
Thank you. duplicated issue.
