### ISSUE TITLE
Can't sell Pair TOMO/BTC

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#157]
**Describe the bug**
Cant sell 

**To Reproduce**
First my balance 15 Tomo you see screenshot
My addres testnet https://scan.testnet.tomochain.com/address/0x416e76e46b99ae8b3bdc85941ded350f07204503

1. Go to pair Tomo/Btc
2. Set amount 1 Tomo
3. Click sell
4. See eror
![Screenshot_2020-03-04-06-35-43-34-picsay](https://user-images.githubusercontent.com/59077947/75830372-3cf6fb80-5de3-11ea-8cd9-16e3fe138ba0.jpg)

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5
Thx regards

**Comment by thanhson1085** [comment]
You have to make order > 1 TOMO, it no

**Comment by thanhson1085** [comment]
You have to make order > 1 TOMO, it messaged you, the quantity trade is too small
