### ISSUE TITLE
Eror Price

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#158]
**Describe the bug**
Eror price sell
**To Reproduce**
1. Go to order place set price 0.00000001 BTC amount 2 tomo
2. Click on Sell
3. See order filled at a very far price 

**Screenshots/Video**
![Screenshot_2020-03-04-06-51-57-41o](https://user-images.githubusercontent.com/59077947/75831157-60bb4100-5de5-11ea-9e59-91c717e4f099.jpg)

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5
Thx regards

**Comment by thanhvk** [comment]
Hi @WhaleCMD 
This is not a bug, the matching engine always finds the best price for traders.

**Comment by 0xwhalerush** [comment]
but the display in the order history does not show matching engine always finds the best price for traders.

**Comment by thanhvk** [comment]
normally your order may be split into multiple sub orders  (or trades) with the different prices (the prices may be better or equal your expectation price), Order history to display your order with your expected price and in Trade history show details your order.

**Comment by 0xwhalerush** [comment]
but the price at that time the buy order was at 0.00005201 BTC when I tried to sell at the price of 0.00000001 BTC the order was filled. ink is quite strange isn't it

**Comment by thanhvk** [comment]
0.00000001 BTC is in Order history? so what is the price in Trade history?

**Comment by 0xwhalerush** [comment]
0.00005201 BTC real time price on dex

**Comment by thanhvk** [comment]
Order history display your expectation price
Trade history display real price when order filled

So, What do you want?

**Comment by thanhson1085** [comment]
The orders will be matched at maker's price
