### ISSUE TITLE
Order History and Trade History No same

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#159]
**To Reproduce**
1. Go to Tomo/usd Order History Trade History
2. Click on sell price 0.001 usd
3. See Order History Trade History no same

![ok2](https://user-images.githubusercontent.com/59077947/75832879-f48f0c00-5de9-11ea-9f2e-8955b1448db7.jpg)
![ok](https://user-images.githubusercontent.com/59077947/75832883-f8bb2980-5de9-11ea-9e42-c06a4c1baaf4.jpg)
![ok](https://user-images.githubusercontent.com/59077947/75832888-fc4eb080-5de9-11ea-9e02-f9fdb82ab411.jpg)

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5
Thx regards

**Comment by thanhson1085** [comment]
No issue here. Order history and Trade history is not same. The order will be matched at maker's price.

**Comment by 0xwhalerush** [comment]
Okay

Regards
