### ISSUE TITLE
Gas setting no work

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#163]
**Describe the bug**
Gas setting
**To Reproduce**
1. Go to click send
2. Click on show gas setting
3. Edit gas setting , i try 21500 
4. Click send
5. Check txid 
6. No same gas 

Txis transaction
https://scan.testnet.tomochain.com/txs/0x784101bff2599c857e1ee929d20619317802fcfe3127d0ea2ea1835d4dd2b3d8

![Screenshot_2020-03-04-17-32-08-87](https://user-images.githubusercontent.com/59077947/75871175-bcfe7f00-5e3e-11ea-9ed1-f1dea34b4eb5.png)

![Screenshot_2020-03-04-17-32-01-80](https://user-images.githubusercontent.com/59077947/75871156-b3751700-5e3e-11ea-8d61-da60e85a81a4.png)

**Comment by thanhvk** [comment]
Gas setting to set ```gas limit``` it's mean maximum gas can use for tx not real gas used.

**Comment by 0xwhalerush** [comment]
No bug?

**Comment by thanhvk** [comment]
yes

**Comment by 0xwhalerush** [comment]
Hmmm okay 
Check all my issue
