### ISSUE TITLE
Amount is fixed to whole number (Tomo/BTC pair)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#165]
Hello. I noticed that under TOMO/BTC pair, the maximum amount that i can execute is fixed to a whole number. You can see my available tomo here as 5.994 TOMO. But as i click the box, the maximum amount i can put as indicated is fixed to 5 Tomo unlike in the other TOmo pairs. I also tried to click the percentages but it only gives whole number and no decimal so that i cant execute all my orders 100% unlike in other pairs. This is also maybe the reason why the amounts on  orderbook at this pair is fixed to whole number. I expect i can execute 100% of my order including the decimals just like in the other pairs.

![duday](https://user-images.githubusercontent.com/46350890/75882264-c8ac6e80-5e5b-11ea-9b32-cd6ce1fd5298.png)

**Comment by thanhson1085** [comment]
We do not consider it as an issue.
Currently, we determine the precision of Max field following the price of the token.
