### ISSUE TITLE
Address Not Accesible in Dex Via Tomowallet

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#167]
In dex via web browser, when you click the coin it will redirect you to tomoscan which will show you its Infos including the address. In dex via tomowallet, when you click the coin, it should also redirect you to tomoscan to access the address and other infos.
![27000EC3-53EB-4593-ABD1-FC2A84E608EA](https://user-images.githubusercontent.com/58533399/76078876-80698980-5fde-11ea-8c32-cbc497140773.jpeg)

**Comment by thanhson1085** [comment]
We do not consider it as an issue. TomoWallet dapp does not support clickable link. It only works on one-page.
