### ISSUE TITLE
Screen cannot be scrolled vertically when try to Inspect Element to see some error.

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#168]
The whole screen cannot be scrolled when try to Inspect Element.

Steps to reproduce:
1. Open the dex
2. Right click on anywhere and Inspect Element
3. The vertical scroll bar cannot be scrolled totally so its hard to see the whole screen.

![orayt](https://user-images.githubusercontent.com/46350890/76140437-5a52f080-6095-11ea-8900-3dbed8214c9d.png)

**Comment by 0xwhalerush** [comment]
Use mouse bro hahaha

**Comment by CryptoChaser13** [comment]
How about no mouse? I use laptop that i can bring anywhere haha.

**Comment by thanhson1085** [comment]
We do not consider it an issue.
As an user, you will not turn on the developer tool.
