### ISSUE TITLE
Every browser refresh always asks for a password

### ISSUE THREAD

**Issue by Dedenwrg** [BuildOnViction/bug-reports#169]
![Screenshot_2020-03-07-16-49-04-72](https://user-images.githubusercontent.com/39203619/76141114-d64c3900-6093-11ea-99c2-0a1a065ac279.png)
When I try to trade and Refresh the browser always asks for a password, that feature should be removed This is troublesome when I'm trading
Website https://dex.testnet.tomochain.com
Wallet adress 0x678e02198C735e5AEf98cC0aFD17703773b838e9

**Comment by 0xwhalerush** [comment]
Lawak aswww

**Comment by thanhson1085** [comment]
It is not an issue. The dex ask the password to make sure you are owning the session.
