### ISSUE TITLE
Settings Window Moves Opposite Side

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#17]
Hello! I’m having trouble with the Settings Window of any indicator in TomoX via TomoWallet. I used two mobile phones to see if its just a problem of my personal phone. The first phone was Oppo A3s Model: CPH1853 Android Version: 8.1.0 Processor: Qualcomm SDM450 Octa Core. When I move the window from left to right, the window moves in the opposite direction, same goes from right to left, the window moves from left to right. 
The other phone was iPhone 6 Software Version: 12.4.4. I can move the window up and down but i’m having trouble with the directions left and right.
The videos cannot be attached in this post, i don’t know why. I can send the videos in telegram if you want. I believe that fixing these small things will make Tomo Dex better than any other dex.

**Comment by thanhvk** [comment]
Hi,

We already know this issue and actually, this is the tradingview library's issue and it still in processing. 

We have created the issue [tradingview not friendly with small screen #195](https://github.com/tomochain/tomox-sdk-ui/issues/195) to track it and we will update when the tradingview library resolves it.

We also plan to use another mobile-friendly chart library on mobile, but not right now.

> The videos cannot be attached in this post, i don’t know why. 

Github support these file:
- PNG (.png)
- GIF (.gif)
- JPEG (.jpg)
- Log files (.log)
- Microsoft Word (.docx), Powerpoint (.pptx), and Excel (.xlsx) documents
- Text files (.txt)
- PDFs (.pdf)
- ZIP (.zip, .gz)

We can close this issue?

**Comment by RonaldDuck** [comment]
So the #195 covers all the errors in window? Is this the same with what i’ve been saying? Even in indicators? If so, you can close the issue, i’ll just wait for the update of the dex 😊

**Comment by thanhvk** [comment]
> So the #195 covers all the errors in window? Is this the same with what i’ve been saying? Even in indicators?

Yes and more, mostly popups (windows) of the chart not responsive and hard to use on small screens like mobile, tablet, laptop 13" additional are some other issues when touch and scroll.

**Comment by thanhson1085** [comment]
> The videos cannot be attached in this post, i don’t know why.

You can use google driver, youtube, .. to upload video, then put the link here.

It is a duplicated issue. Thank you.
