### ISSUE TITLE
notification column redundant

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#170]
**To Reproduce**
1. Place order 1-2 filled
2. Click notifitacion

when taking action on the Tomo dex the notification column only increases, whereas currently only taking 1-2x actions only the notification column is so wide

![IMG_20200308_011927-picsay](https://user-images.githubusercontent.com/59077947/76150486-a9247880-60dd-11ea-8a75-6cce8423f45d.jpg)

**Comment by 0xwhalerush** [comment]
the notification column should increase when we take action.but in this case the column is too redundant when just doing some actions

**Comment by thanhson1085** [comment]
After discussed with team, we do NOT consider it an issue.
We keep the max height of the box.

**Comment by 0xwhalerush** [comment]
but this shouldn't be that big. I suggest every time a new box is added

**Comment by thanhson1085** [comment]
Thanh you for you suggestion. But team decided to keep the current height
of the box, not depends on the number of notifications.

**Comment by 0xwhalerush** [comment]
please see other markets / dex
