### ISSUE TITLE
Chart properties can't close

### ISSUE THREAD

**Issue by cryptomansion** [BuildOnViction/bug-reports#171]
I see on the chart properties has problems,can open but can't closed again. You can notice it with the GIF or picture below :

![BUg-report-TomoDEX](https://user-images.githubusercontent.com/41590820/76151895-366ec980-60ec-11ea-8f0d-5e1abf86012e.gif)

![Screenshot (1492)](https://user-images.githubusercontent.com/41590820/76151932-98c7ca00-60ec-11ea-88c3-c57e53bf6929.png)

**Comment by cryptomansion** [comment]
Tomo address : 0x461B2cBe68B820a386048f0dFb84327615e2c0FE
Thanks regards

**Comment by cryptomansion** [comment]
Tomo address : 0x461B2cBe68B820a386048f0dFb84327615e2c0FE

Thnks regards

**Comment by thanhson1085** [comment]
duplicated https://github.com/tomochain/bug-reports/issues/3
