### ISSUE TITLE
Signature request eror

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#172]
**To Reproduce**
1. Go to https://dex.testnet.tomochain.com/trade/TOMO-USDT
2. Sign in use metamask 
3. Change network 
Network Name : Tomo
Rpc Url : https://rpc.testnet.tomochain.com
Chain id  : 89
Symbol : TOMO
Block explorer : https://scan.testnet.tomochain.com/
*this is according to the rules that I see in the doc

4. Place order buy/sell
5. See signature request metamask. 
Example  I try order buy 2 tomo . but why the signature shows the value of 15 eth , See picture
![IMG_20200309_120429](https://user-images.githubusercontent.com/59077947/76184408-66a68d00-61fe-11ea-8338-bf51e4f2abd8.jpg)

![IMG_20200309_115751-picsay](https://user-images.githubusercontent.com/59077947/76184378-4f679f80-61fe-11ea-91f9-f9b4133ba27f.jpg)

**Comment by thanhson1085** [comment]
Metamask displays your balance. It is not an issue.

**Comment by 0xwhalerush** [comment]
but why "ETH" is not "TOMO"
