### ISSUE TITLE
Question extra reward 

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#174]
excuse me dev TomoChain

Bug bounty Phases 2 resolved get extra reward 200 Tomo?

**Comment by chinhnt23** [comment]
@WhaleCMD Bounty Phase 2 doesn't include extra reward 200 TOMO. You can see more information here: 
https://medium.com/tomochain/tomox-testnet-bounty-program-phase-2-2d86c9001e5c

**Comment by 0xwhalerush** [comment]
:((
