### ISSUE TITLE
Register fail

### ISSUE THREAD

**Issue by bacoor-hb** [BuildOnViction/bug-reports#175]
**Describe the bug**
https://scan.testnet.tomochain.com/txs/0xfa7c1b74bd1f0166f81e12ec47ddad7d26b7b41c00a40ff65d812a683c17eee4
Try register new relayer got fail transaction

**To Reproduce**
=> go to https://relayer.testnet.tomochain.com => sign metamask
1. Go to https://relayer.testnet.tomochain.com/register
2. Input address coinbase: 0xE525BF7E1C84dA956E373903d92aac69bEE46669
3. SAVE & CONTINUE
4. input relayer name: TDEX => SAVE & CONTINUE
5. choose fee: 0.21% => SAVE & CONTINUE
6. Select trading pairs => SAVE & CONTINUE
7. publish
8. confirm transaction on metamask
9. => transaction fail

**Expected behavior**
It should be success transaction !

**Device specification (please complete the following information):**
 - Device: MacBook Pro
 - OS: Mac OS

**Comment by thanhson1085** [comment]
What pairs did you select in the form.

**Comment by bacoor-hb** [comment]
> What pairs did you select in the form.

XRP/TOMO
XRP/USDT

**Comment by thanhson1085** [comment]
Try with the other coinbase address. Seems `0xE525BF7E1C84dA956E373903d92aac69bEE46669` is used in previous registration.

**Comment by bacoor-hb** [comment]
https://scan.testnet.tomochain.com/txs/0x8bd2f080c9b6c79153a35fdf790ca832209d0bfb6b834fb15d35978e26a18aab
try with: 0x96d1d714EDF6E361E5CC5CbABa00689C78D0D552
=> same fail

**Comment by thanhson1085** [comment]
Try coinbase `0x96d1d714EDF6E361E5CC5CbABa00689C78D0D552` with pairs:
XRP/TOMO
XRP/USDT
USDT/TOMO

You use XRP/USDT, so USDT will be required to pair with TOMO, then tomox can calculate the price of USDT, and pay fee TOMO for masternode.

**Comment by bacoor-hb** [comment]
https://scan.testnet.tomochain.com/txs/0xf8a6627bce57f5f6cd71a7f50416ad76d229670ca87712a61418e57e775f1e09
transaction success
![image](https://user-images.githubusercontent.com/37326129/77055377-5911b400-6a03-11ea-96cf-0125a26cfb2e.png)

**Comment by thanhson1085** [comment]
Yep, thank you for the report.
So the issue here:
- No validated inputs: https://github.com/tomochain/tomorelayer/issues/73
- Register failed some https://github.com/tomochain/tomorelayer/issues/72
