### ISSUE TITLE
Overlapping of chart on tomodex through tomowallet.

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#176]
Hello. I have seen the chart not organized 
since there is overlap betweek the chart parts as you can see below in this pic. 

![20200319_215542](https://user-images.githubusercontent.com/46350890/77074888-b891a480-69ae-11ea-99e0-597a40e149c8.jpg)

![20200319_215527](https://user-images.githubusercontent.com/46350890/77074932-c9421a80-69ae-11ea-8efc-9918a01ee49a.jpg)

**Comment by thanhson1085** [comment]
We do not consider it as an issue.
You should select the other candle side 1h, 2h for better view.

**Comment by CryptoChaser13** [comment]
I tried 1h sir

![Screenshot_20200320-104159_Tomo Wallet](https://user-images.githubusercontent.com/46350890/77131730-f24bc500-6a19-11ea-92b9-1af3e7e8c925.jpg)

![Screenshot_20200320-104236_Tomo Wallet](https://user-images.githubusercontent.com/46350890/77131723-e95af380-6a19-11ea-9b4c-da02e03ef910.jpg)

**Comment by thanhson1085** [comment]
We do not consider "Overlapping text with candle" as an issue.
