### ISSUE TITLE
Fee taker

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#178]
Why in dex there is no Fee trade/takers column on trade history/order , is there no fee? or you forget
I suggest holding a fee column so everyone can find out
or you can write a fee above the buy / sell button

Example 
![Screenshot_2020-03-23-23-45-10-71-picsay](https://user-images.githubusercontent.com/59077947/77340981-a1610700-6d60-11ea-9171-313c35aa86d6.jpg)

**Comment by 0xwhalerush** [comment]
@thanhson1085

**Comment by 0xwhalerush** [comment]
@thanhvk @chinhnt23

**Comment by thanhson1085** [comment]
Same as the others exchange, we will not show the fee in that buy/sell part
