### ISSUE TITLE
Order ID 0 order by "Market " or directly buy/sell on txhash

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#179]
**To Reproduce**
1. Go to buy/sell market or directly
2. Click on order history and see tx hash trade 
Order "market" or directly buy/sell
every order market /limit should have an order number to avoid mistakes

Txid : 
https://scan.testnet.tomochain.com/orders/0xd74b919365d3a6c32a5719984ff3314fa8116a9a957ab30fd21643c0a681e9da
![Screenshot_2020-03-23-23-32-31-51-picsay](https://user-images.githubusercontent.com/59077947/77341367-32d07900-6d61-11ea-931e-3d8e85e18179.jpg)

Order limit 
Txid : 
https://scan.testnet.tomochain.com/orders/0x7a3d14537c8d01f03afca8754bb9535c77788d8a5693e32ed2532c66ab13dfc5
![Screenshot_2020-03-23-23-55-12-12](https://user-images.githubusercontent.com/59077947/77341751-c9049f00-6d61-11ea-9900-7b1945e29f80.png)

**Comment by 0xwhalerush** [comment]
@thanhson1085 @thanhvk

**Comment by 0xwhalerush** [comment]
@chinhnt23

**Comment by thanhson1085** [comment]
There is no issue here. All taker order will do not have orderId (orderId=0)

**Comment by 0xwhalerush** [comment]
but I think every order place,   cancel and filled has an order ID. You can see in other markets
