### ISSUE TITLE
Additional Security for the Wallet

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#18]
I want to suggest a feature to add more security for the tomowallet. Is it possible to implement an authenticator? There are various ways to authenticate. SMS, Google Authenticator and Authy Authenticator. I think it is quite easy to send funds with just a password, i believe that an authenticator will add more security. I hope this has not been submitted yet. Thanks for hearing me out 😊

**Comment by thanhson1085** [comment]
Thanks for the report. But SMS, Google Authenticator will not be applied for a decentralized wallet that stores the private key in the client.
