### ISSUE TITLE
Tieng Viet not working

### ISSUE THREAD

**Issue by Samy940** [BuildOnViction/bug-reports#19]
![Screen Shot 2020-01-07 at 12 52 41 PM](https://user-images.githubusercontent.com/59605088/71890930-10f62b80-314e-11ea-8a66-ef24865f07b5.png)

Hi, 

When i change to Tieng Viet is not translating the pages. (see selected language in upper right corner)
The language translations are available only on home page and only for the menu tab (the 4 in the left). But the translations need to appear everywhere.
This was tested on a Chrome. My wallet is: 0xbcabd6041abf288147961645a5a5f5557c9e8ff1

Thank you, 
Samy

**Comment by thanhvk** [comment]
Hi,

We already know it, the localization (language translate) feature not yet complete. We also created the issue [#143](https://github.com/tomochain/tomox-sdk-ui/issues/143) for this feature thank you.

**Comment by Samy940** [comment]
I am happy to hear that you already know about it and it's not resolved yet.  But it was not reported by anyone. 
And to be honest your task #143 does not say that the language is not working, it just says that you need to translate an excel file. That can mean lots of things. 
So, this is a bug :) or make a better communication about what testing means for you. Otherwise, the translation is that everything that does not work and it's not added by someone else here: https://github.com/tomochain/bug-reports/issues --> equals that it qualifies for your contest. 
Let's not play around please! Thank you in advance.

**Comment by thanhvk** [comment]
I said the language feature not yet complete doesn't mean it's not working, actually, you can see it already working but not yet complete because we still need to translate all keywords from English to other languages like Tieng Viet, ... And issue #143 for that.

This is not playing around :smile: thank you.

**Comment by thanhson1085** [comment]
It is not an issue, multi languages works, just need more translation.
