### ISSUE TITLE
TypeError: Cannot read property 'quoteTokenDecimals' of undefined

### ISSUE THREAD

**Issue by gCrypto90** [BuildOnViction/bug-reports#2]
Hi, 

Unlocked wallet, changed view from Markets to Wallet view, an error appeared:
'TypeError: Cannot read property 'quoteTokenDecimals' of undefined'

Details:
Device: MacBook Pro (15-inch, Late 2011)
Operating system: MacOS Sierra version 10.12.6
Browser: Google Chrome, Version 78.0.3904.108 (Official Build) (64-bit)
T-shooting: Cleared cache, used incognito 
Wallet address: 0xe42099320518d311ad7fd15563eafd09aa439fdc

![Screen Shot 2019-12-19 at 3 14 06 PM](https://user-images.githubusercontent.com/59055830/71178155-3a6e1680-2276-11ea-96d0-cc45b1dcf57b.png)

Thanks!

**Comment by thanhson1085** [comment]
We can not reproduce the issue, this issue also logged here: https://github.com/tomochain/tomox-sdk-ui/issues/164

https://imgur.com/CUl9kNj

Can you show the video for your steps?

**Comment by thanhson1085** [comment]
We can not reproduce it. Feel free to reopen if you can provide more information. Thank you.
