### ISSUE TITLE
PrivateKey shouldn't be displayed here

### ISSUE THREAD

**Issue by matheoCrypto99** [BuildOnViction/bug-reports#20]
![private key](https://user-images.githubusercontent.com/59606171/71892261-35073c00-3151-11ea-89db-dc4ca60abf95.JPG)

Testing browser: Google Chrome

I've searched a while and i discovered a critical issue in terms of account security. 

That privateKey i have highlighted in the above picture, shouldn't be displayed there even if it's an encrypted key or not. Usually is much better to prevent things to happen than to display more details than it's needed.

P.S.: and yes that address it's my wallet address.

My wallet: 0x7AF113e499AA868Fb200696983b237c0ac947F34

Thanks!

**Comment by thanhson1085** [comment]
The key is encrypted with the pin code. We do not consider it as an issue.
