### ISSUE TITLE
Can't go back to the dex home page

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#21]
I cant back to home page dex
Issue :
1. I clik back 1x no respon 2xclik no respon 3xclik back to nemu dapps/wallet

You see picture and video
![IMG_20200111_022749](https://user-images.githubusercontent.com/59077947/72180554-feb01200-3419-11ea-845c-d038c04ddc4e.jpg)

Video
https://streamable.com/es5vg

You can try this on another device
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

Thanks

**Comment by 0xwhalerush** [comment]
Device Type / Model: Mobile Phone / CPH1729

**Comment by thanhson1085** [comment]
No "back" button here. It is a popup, just click "close" button on the top right corner.
