### ISSUE TITLE
Can't see Funds and no scroll up/down button

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#23]
Hello. May i ask, ask you can see i have available btc amount to trade but i cannot see it on funds as i have encircled below. I would also like to scroll it down but i cannot because i can't do it. If i just mistaken, hope you can clear it here.
![No scroll button](https://user-images.githubusercontent.com/46350890/72322766-bf174d80-36d9-11ea-8cd5-c892c9577054.png)

**Comment by thanhvk** [comment]
yes, this is a UI issue of Orders table and we have created the issue [#189 ](https://github.com/tomochain/tomox-sdk-ui/issues/189) for that before.

**Comment by CryptoChaser13** [comment]
But my issue is not the increase of size, but rather the funds which are not indicated

**Comment by thanhvk** [comment]
this issue happen on the small screen because the Orders table's height, not enough so you can see your funds, you can try it on a larger screen.

**Comment by CryptoChaser13** [comment]
But i can see my orders there sir, order history and even trade history

**Comment by thanhson1085** [comment]
The min height of the order table is not fixed, so you can not see your order history or funds if your screen is small.
Duplicated issue https://github.com/tomochain/tomox-sdk-ui/issues/189
