### ISSUE TITLE
Some Indicator Setting buttons get lost

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#25]
I tried to add an indicator. Then i clicked its settings so right now i am seeing this picture under Styles with Defaults, Ok, and Cancel button below:
![Uploading 20200114_161252.jpg…]()

Then i clicked Inputs and here is the picture, everything is normal:
![Uploading 20200114_160613.jpg…]()

And as i go back to styles again, the Defaults, Ok, and Cancel buttons are missing and tried several times. The picture is shown here:
![Uploading 20200114_161320.jpg…]()

If im not mistaken, this becomes a bug especially if traders use indicators for their trade.

**Comment by CryptoChaser13** [comment]
I just uploaded a video when i did it:

http://imgur.com/gallery/Q9wCGRN

**Comment by thanhson1085** [comment]
Can you update the images, we can not see it.

**Comment by CryptoChaser13** [comment]
Okay ill send here again

**Comment by CryptoChaser13** [comment]
Here is the first picture:

![Uploading 20200114_161252.jpg…]()

**Comment by CryptoChaser13** [comment]
Seems i cant upload the picture here, it just says uploading. Can i just upload it on imgur and paste the link here?

**Comment by thanhson1085** [comment]
You have to wait until finishing the upload. You should update the description of the issue, do not need to create new comment.

**Comment by CryptoChaser13** [comment]
It took me an hour waiting last time when i uploaded it. It just says uploading but comment button is available already.

**Comment by CryptoChaser13** [comment]
Done updating

**Comment by CryptoChaser13** [comment]
If you cannot see the photo. You can just play the video i submitted. https://github.com/tomochain/bug-reports/issues/25#issuecomment-574064507

**Comment by thanhvk** [comment]
@MirasolFerrer I watched your video and I think this is an issue of the TradingView library.

Recently, I have updated the TradingView library to version 1.15 at commit https://github.com/tomochain/tomox-sdk-ui/commit/8fec25ecd093ccbfe88368b856fcbf96fff4a5a9 and I see it have some new UIs for setting popup (you can see image below) and this issue maybe not happen on new version (v1.15).

![v1 15_settings_popup](https://user-images.githubusercontent.com/11411161/72403684-96e52880-3785-11ea-8b0a-ce71844fa8bc.png)

For now, the new code only available on the devnet. But you can see new version of the TradingView library in here https://charting-library.tradingview.com/

**Comment by CryptoChaser13** [comment]
I have been wathing this issue since then but all i thought it was a poor network connection but now i confirmed its really the dex issue

**Comment by CryptoChaser13** [comment]
Hope to receive at least any reward for figuring that sir @thanhvk

**Comment by CryptoChaser13** [comment]
Dear sir @thanhvk 0x9a3432d83d657f29e790aa163e76695f11d19bd4

**Comment by thanhson1085** [comment]
We use TradingView Library for charts and the indicator. We do not consider it as an issue. Thank you.
