### ISSUE TITLE
change the color on the depth graph of "JS chart by amcharts"

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#27]
![tomo dark](https://user-images.githubusercontent.com/38444647/72415714-02dc8680-37b0-11ea-9d84-02b6f1c39edb.png)
![tomo light](https://user-images.githubusercontent.com/38444647/72415715-03751d00-37b0-11ea-8af4-16f77c66b0f1.png)

as we can see when we hit the darkmode we can notice the name it should be on light colors for better viewing. thank you

**Comment by thanhson1085** [comment]
Thank you for the suggestion. The text is from the chart library, we do not consider it as an issue.
