### ISSUE TITLE
Additional improvements on markets tab.

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#28]
maybe we can sort this highlights with red to see the top 24h volume, 24h low. 
![tomosort](https://user-images.githubusercontent.com/38444647/72416156-015f8e00-37b1-11ea-9b00-dd168e1322cd.png)

**Comment by thanhvk** [comment]
this is duplicate with https://github.com/tomochain/tomox-sdk-ui/issues/174
