### ISSUE TITLE
Deposit blank page on https://relayer.testnet.tomochain.com

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#30]
I use browser and dapps same blank
![Screenshot_2020-01-15-15-38-46-14](https://user-images.githubusercontent.com/59077947/72418318-2b16b600-37ad-11ea-8978-6524a531523e.png)
![Screenshot_2020-01-15-15-36-38-30](https://user-images.githubusercontent.com/59077947/72418320-2baf4c80-37ad-11ea-9b1a-3bb4c1fdc783.png)

You see video
https://streamable.com/ev76k

My issue :
1. I deposit 30 tomo on my addrees through the faucet and then I deposit to the relay as much as 1 tomo 10x
2. then it becomes blank, I have tried it on several other devices. the result is the same as blank

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by thanhson1085** [comment]
I can not reproduce the issue with my relayer.
You created a new relayer with 30 TOMO, right?
And what is your address that you are using to create the relayer?

**Comment by 0xwhalerush** [comment]
My wallet has 30 tomo and I deposit it into a relay, then the deposit menu becomes blank like that, I've tried it on other devices

**Comment by 0xwhalerush** [comment]
> I can not reproduce the issue with my relayer.
> You created a new relayer with 30 TOMO, right?
> And what is your address that you are using to create the relayer?

Addres relayer Address: 0x6Dc42C8A23d525C3bdA17BDf6fAe72bd51a41FEF

**Comment by WhaleCMD** [comment]
1. I was given 25000 tomo to deposit to the relay
 2. then I claimed 30 of the faucet to deposit again to the relay
 3. to be blank

**Comment by thanhson1085** [comment]
Did you try to use your relayer on desktop?
TomoRelayer does NOT support Mobile.

**Comment by WhaleCMD** [comment]
I use computer and dapps same blank
You can try bro
I can send phases wallet testnet me for you

**Comment by thanhson1085** [comment]
Still can NOT reproduce: https://youtu.be/uXapTJwiBo8
Hope you can provide a video that you use DESKTOP to produce the issue. Thank you.

**Comment by 0xwhalerush** [comment]
1. I deposit to tomo relayer as much as 1 tomo 
2. After clicking the deposit page becomes blank 
3. I tried with another wallet it turned out the same after deposit wallet to tomo relayer page deposit blank

**Comment by WhaleCMD** [comment]
if unsure, please check pm, and can use the wallet that I use on tomo relayer for deposit and see the deposit menu

**Comment by thanhson1085** [comment]
> I deposit to tomo relayer as much as 1 tomo
> After clicking the deposit page becomes blank
> I tried with another wallet it turned out the same after deposit wallet to tomo relayer page deposit blank

I followed this steps but can NOT reproduce the issue.

Hope you can upload the video that you do the steps on DESKTOP version.

**Comment by WhaleCMD** [comment]
Wait

**Comment by 0xwhalerush** [comment]
See video
https://streamable.com/jdvl2

**Comment by 0xwhalerush** [comment]
You can try to find any deposit to relayer on configuration > deposits> then right deposit>

**Comment by thanhson1085** [comment]
I followed your steps, but can NOT reproduce your issue: https://streamable.com/ewisj
Feel free to open it if you can provide more details.

**Comment by 0xwhalerush** [comment]
In the video you do not do to tomo relayer! How this bug occurs
I see you no deposit
Only clik deposit no deposit

**Comment by thanhson1085** [comment]
I deposited 1 TOMO for the relayer. But did NOT get the issue.

**Comment by 0xwhalerush** [comment]
Please make a deposit of 10x very quickly

**Comment by thanhson1085** [comment]
" make a deposit of 10x very quickly", this case is unreal. 

But we can send you 30K TOMO testnet, then you records the videos that contains ALL steps you did to produce the issue.

**Comment by 0xwhalerush** [comment]
Wait i creat video again

**Comment by thanhson1085** [comment]
@WhaleCMD , let us know if you can provide more details. I will keep the issue open and follow it up. thank you.

**Comment by WhaleCMD** [comment]
Okay bro

**Comment by WhaleCMD** [comment]
> " make a deposit of 10x very quickly", this case is unreal.
> 
> But we can send you 30K TOMO testnet, then you records the videos that contains ALL steps you did to produce the issue.

I cant register again bro

**Comment by 0xwhalerush** [comment]
You can try setting update trade fee 0.2% and deposit
My txid update trade fee https://scan.testnet.tomochain.com/txs/0x9f31b0e116685d4d072f05a44e248a16072f4872ae0e9e8ff04c282071e6fd1a



Txid deposit on relayer
1. https://scan.testnet.tomochain.com/txs/0x3344e1cf95d3caa5bd75cec66bcb1f546708bea6445521da5cf1d5c1a60173fd
2. https://scan.testnet.tomochain.com/txs/0x37b64bf3955e1a0e6b80ce1e85cb03ee6dbb837c7fe377f9904b104bac3352c1

3.https://scan.testnet.tomochain.com/txs/0x0766e91710b0f022c55f4518440759008f94cd4ce341905c57a1df2e1543221a

And blank menu deposit
https://streamable.com/jdvl2

**Comment by WhaleCMD** [comment]
Owner relayer coinbase https://scan.testnet.tomochain.com/address/0x3e96fd2d06ca69e5f1423729725973de3d2cebbe

**Comment by thanhson1085** [comment]
We can NOT reproduce the issue. We will keep the issue open to follow it up.

**Comment by 0xwhalerush** [comment]
Deposit > update fee 0.2% > deposit again > update fee 0.2% > deposit again >update fee 0.2% >deposit 1.1111111111111112 Tomo https://scan.testnet.tomochain.com/txs/0x0766e91710b0f022c55f4518440759008f94cd4ce341905c57a1df2e1543221a

if you have not been able to process this problem, please update my fees and deposit this issue occurs
![Screenshot_2020-01-31-13-17-54-87](https://user-images.githubusercontent.com/59077947/73516790-2a785380-442c-11ea-889b-167563871e7e.png)

**Comment by 0xwhalerush** [comment]
+claim tomo on faucet before you deposit

**Comment by 0xwhalerush** [comment]
![Screenshot_2020-01-31-13-32-09-25](https://user-images.githubusercontent.com/59077947/73517469-20575480-442e-11ea-8e15-881fd9c4fea1.png)

**Comment by thanhson1085** [comment]
Thank you for the information. Your issue is not easy to reproduce, we will try to reproduce it when we have more time. we will keep it open to follow it up. Do NOT rush us, thank you.

**Comment by thanhson1085** [comment]
Thank for the help from issue https://github.com/tomochain/bug-reports/issues/120

Confirmed with LOW severity @victorngn

**Comment by 0xwhalerush** [comment]
Okay thanks

Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by chinhnt23** [comment]
@WhaleCMD I have sent you Bounty Reward for this issue. Thanks

**Comment by 0xwhalerush** [comment]
Okay thanks bro

**Comment by thanhson1085** [comment]
Resolved @chinhnt23

**Comment by 0xwhalerush** [comment]
Thx

**Comment by 0xwhalerush** [comment]
When extra 200 TOMO will be sent? within 1 business day after the confirmed issue is resolved

**Comment by chinhnt23** [comment]
@WhaleCMD We are checking and send ASAP, sorry for the delay

**Comment by WhaleCMD** [comment]
Okay i waiting you

**Comment by 0xwhalerush** [comment]
@chinhnt23 how news update?

**Comment by 0xwhalerush** [comment]
0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5
My addres

**Comment by chinhnt23** [comment]
@WhaleCMD  I have issued the Extra Bounty for the resolved issue, please check your wallet

**Comment by 0xwhalerush** [comment]
Thx bro
