### ISSUE TITLE
Unclear ' Show Receipt' button when switched to light mode

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#31]
I tried to send some tomo on dark mode. After successfully sent, i can see the 'Show Receipt' button very clear below, 

![unclear 2](https://user-images.githubusercontent.com/46350890/72419732-455f7e00-3732-11ea-86ab-2ef82b92c59f.png)

The same thing, i tried to send some tomo again, but this time i enabled light mode, unfortunately, the 'Shoe Receipt' button is unclearly seen and cannot be easily found. 
![UNCLEAR 1](https://user-images.githubusercontent.com/46350890/72419845-6fb13b80-3732-11ea-90c2-903d34e3101c.png)

This i think can give some wallet users a hard time in finding the proof of transaction or the receipt when they enable light mode. I suggest the 'Show Receipt' button must use a white colored font when in light mode.

**Comment by thanhson1085** [comment]
Duplicated issue: https://github.com/tomochain/bug-reports/issues/26

**Comment by CryptoChaser13** [comment]
Hello sir @thanhson1085 I hope you dint mind me asking, Why is it a duplicate issue? I think its a different part of the exchange where ive seen the bug.

**Comment by thanhson1085** [comment]
In issue https://github.com/tomochain/bug-reports/issues/26, it already mentioned the issue with Recieve/Send, ... popup windows in light mode

**Comment by CryptoChaser13** [comment]
It indicated the 'Show Receipt' button sir?

**Comment by thanhson1085** [comment]
'Show Receipt' is in Send popup windows.
