### ISSUE TITLE
Error message for placing order with high Sell Price

### ISSUE THREAD

**Issue by UmckaBear** [BuildOnViction/bug-reports#32]
The issue is connected with new order and big Sell Price value. When you put big sell price and create new order, you receive error message:

![SellPrice](https://user-images.githubusercontent.com/31537952/72453089-3e367f80-37c7-11ea-9e35-562dfede8749.jpg)

For example in case of "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333555555555555555555555555555555555555555555555555555555555555555555555555555555555555555553333333333333333333333333333333333333333" price we will receive: 
`invalid BigNumber string value (arg="value", value="3.3333333333333333e+235", version=4.0.38)`

In case of more then 302 symbols:
`invalid BigNumber string value (arg="value", value="Infinity", version=4.0.38)`

Same issue can be with big numbers in other fields, but it is possible only check with high sell price due balance.

There should be normal warning message instead of code and it should be limitation in sell price

**Comment by thanhvk** [comment]
At commits https://github.com/tomochain/tomox-sdk-ui/commit/ce50906bebaf31b74a475d0f48f6a47f584b04c2 & https://github.com/tomochain/tomox-sdk-ui/commit/481d6590863151c3d442afb22956dc9e2a178937 when I use BigNumber library and refactor code this error is resolved. You can see the image below:

![Screenshot from 2020-01-17 09-35-51](https://user-images.githubusercontent.com/11411161/72581028-7bf2ef80-3910-11ea-8470-f2ba4cd668c8.jpg)

**Comment by UmckaBear** [comment]
@thanhvk Thank you for quick response. 

As I can see on screenshot you can't create order due balance and received message "Your balance is not enough". 
On video below in current version https://dex.testnet.tomochain.com you also will not receive any errors in case of invalid balance. Only in case successful try to create order.

https://drive.google.com/file/d/1U63AR8HZs5Ne-SQfJ-Y-bQeKeG85R7rI/view?usp=sharing

Could you please recheck using enough balance to be sure that https://github.com/tomochain/tomox-sdk-ui/commit/481d6590863151c3d442afb22956dc9e2a178937 fully fixed it and you successfully created new order.

I can't check it due 0 balance on devnet.tomochain.com network.

**Comment by thanhvk** [comment]
thank you for your video, I checked again, this is a bug

**Comment by thanhson1085** [comment]
confirmed @chinhnt23

**Comment by UmckaBear** [comment]
My wallet: 0xD273485Bdedeb856083DDe9A8b293aa556cf8178

Thank you.

**Comment by chinhnt23** [comment]
@UmckaBear Thank you, We are processing your bounty

**Comment by thanhson1085** [comment]
@UmckaBear this issuse was resolved, what is your wallet address for the bounty?

**Comment by UmckaBear** [comment]
My wallet: 0xD273485Bdedeb856083DDe9A8b293aa556cf8178

Thank you.

**Comment by thanhson1085** [comment]
Done
