### ISSUE TITLE
request password for security enhancement while trading plus disclaimer for country restriction

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#34]
I just want to ask where to we used this temporary password when we login to the exhange?
![tomo-login](https://user-images.githubusercontent.com/38444647/72485179-d7a27780-3841-11ea-8995-eb558614f939.png)

My suggestion is to add this password feature when we login to the tomodex exchange.

- The function of the password is when we idle for a 1 min or any time set by the team;  the trade function like buy or sell will need to be unlock by the password we enter during login on the page when we put our pvt key or Mnemonic Phrase.
- Its give more security when we forgot to logout on the page , case scenario when we share computer in our house and then suddenly our kids used it, this avoid accidentally selling our precious assets.
- During locking the exchange we can continue to explore the whole pages, but when we need to buy or sell coins or tokens, there will be a popup where we need to put the password to be able to sell or buy, then that's the case the whole pages will be unlock if we put the right password.
![tomo01-16-2020](https://user-images.githubusercontent.com/38444647/72485823-face2680-3843-11ea-986a-041343981072.png)

----------also this message should put, if the exchange have restriction on certain country-----

![vitex01-16-2020](https://user-images.githubusercontent.com/38444647/72486373-a7f56e80-3845-11ea-9ff5-117286bcd457.png)

**Comment by thanhson1085** [comment]
Thank for your suggestion, but we do not consider this improvement at this time.
