### ISSUE TITLE
No minimum Trade is put on ! and Max buy set always to 0 on XRP/tomo

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#35]
In the image below its say max 0 but i still have tomo balance when i click the amount field. Its not automatically compute how many xrp you can buy.
![tomobug01-16-2020](https://user-images.githubusercontent.com/38444647/72487412-e3de0300-3848-11ea-8632-e3d29becafa6.png)

No minimum trade put on. I put the link of my video where i buy 1 xrp and its rejected and i don't know what is the error maybe we put details why its rejected on the order history and put some message how much the minimum trade on the certain pair. link of the video below.
https://www.youtube.com/watch?v=t4Y-OUFq-aY

**Comment by zillabytes** [comment]
This is for eth/tomo pair. its changes when we click on amount on buy/sell and the amount is change on max. while on xrp/tomo pair on buy its always 0.
![ethbugtomo](https://user-images.githubusercontent.com/38444647/72579849-40a6ef80-3915-11ea-974a-ae2eac5ae364.png)

**Comment by thanhson1085** [comment]
Issue Max always 0, duplicated https://github.com/tomochain/bug-reports/issues/41
Issue Minimum amount, duplicated https://github.com/tomochain/bug-reports/issues/36
@zillabytes , should not input 2 problems in an issue you create.
