### ISSUE TITLE
All Market Sorting

### ISSUE THREAD

**Issue by JO-naz** [BuildOnViction/bug-reports#37]
I dont know if its already in the plan to add market sorting if not then i will suggest adding it.
Market sorting is always a very usefull tool for traders.
![b8e887c80248c98d9fcc570c8edb1ae7](https://user-images.githubusercontent.com/42189282/72497853-ab4e2180-3868-11ea-9b8e-6afbc23c6c4a.png)

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/bug-reports/issues/28. Thank you.
