### ISSUE TITLE
'(Version=4.0.38)' pop-up when try to send tokens but insufficient funds

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#38]
I tried to send some tomo tokens but i adjusted the gas that could make my funds insufficient to be sent. But i got this pop-out message of Insufficient funds beside it '(Version=4.0.38)'. Some wallet users may  ask what is this code whenever they encounter this so ill try to submit it as bug
![tomo daw](https://user-images.githubusercontent.com/46350890/72522919-93987e00-3813-11ea-960c-2f884a5110fc.png)

**Comment by thanhvk** [comment]
thank you, but we don't think this is an issue :smile:

**Comment by thanhson1085** [comment]
We do not consider it as an issue. thank you
