### ISSUE TITLE
ADA/TOMO pair MAX is 0

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#40]
another ada/tomo pair not calculating the max can buy its always say 0 even i have enough tomo to buy.
![adatomo pair](https://user-images.githubusercontent.com/38444647/72589470-4b25b100-3936-11ea-9c01-f0033a0fd834.png)

screenshot found below

**Comment by thanhvk** [comment]
this is duplicate https://github.com/tomochain/tomox-sdk-ui/issues/181
