### ISSUE TITLE
ETH/BTC pair and XRP/BTC pair MAX can buy 0

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#41]
another 2 pairs got the same issue of max can buy is 0 even have amount of btc
![eth-btc](https://user-images.githubusercontent.com/38444647/72590130-0864d880-3938-11ea-939e-31259c65bd17.png)
![xrpbtc](https://user-images.githubusercontent.com/38444647/72590131-0864d880-3938-11ea-8b03-a56817ae5139.png)

**Comment by thanhvk** [comment]
this is duplicate https://github.com/tomochain/tomox-sdk-ui/issues/181
