### ISSUE TITLE
Potfolio shows negative value on "Available amount" and amount in orders exceeds total balance

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#43]
Hello. I tried to trade all my tomo to buy eth and have made trades 25% until all my tokens will be put into order. I have clicked it as many times as it reaches "Not enough balance" state. So now my orders are being executed. But as i checked with my portfolio, amount in orders is more than my total balance making my available balance as negative. The picture is shown below:  
![new bug](https://user-images.githubusercontent.com/46350890/72596821-1bc77200-393f-11ea-9093-90d8ec807070.png)

**Comment by thanhvk** [comment]
duplicate https://github.com/tomochain/tomox-sdk-ui/issues/206
