### ISSUE TITLE
Data Fields on buy and sell order not clearing when selecting other pairs

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#44]
When i select other pairs the data fields of buy and sell order is not clearing.

I tested by setting up 25% then select other pairs but the fields still the same amount when i select from previous pair of 25%

it should be cleared when selecting other pairs or the page should refresh when selecting other pairs.

here's the link of the video I uploaded on Youtube.
https://www.youtube.com/watch?v=QBvG1tLKmro

**Comment by thanhvk** [comment]
duplicate https://github.com/tomochain/tomox-sdk-ui/issues/205
