### ISSUE TITLE
Can't full screen the site in mobile device

### ISSUE THREAD

**Issue by darryl06** [BuildOnViction/bug-reports#45]
![Screenshot_20200118-181344](https://user-images.githubusercontent.com/42299210/72662549-881ba180-3a23-11ea-9b4b-124b5583be9c.png)
![Screenshot_20200118-181155](https://user-images.githubusercontent.com/42299210/72662550-881ba180-3a23-11ea-9121-841b336ffe20.png)

Can't full screen the website on mobile device,and I try too to switt on desktop mode,and didn't full the screen,I think you need to fix this for better experience of traders, because many traders using mobile also,for example when thier outdoor

Tomo address
0xeff3a24f334ccc2a20f73d76535e4efee184b410

**Comment by thanhson1085** [comment]
On DApp mobile version, tomoDex will not support to view chat in fullscreen. thank you.

And, You have to use TomoDEX in TomoWallet Dapp.
TomoDEX does support mobile browser.
