### ISSUE TITLE
Additional Space for Dex

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#46]
Hello! I just want to suggest something. I've noticed that the exchange has a limited space, I feel like I need to see more. It will be nice if you will add more space at the bottom of the page. It will also help the (OPEN ORDERS, ORDER HISTORY, TRADE HISTORY AND FUNDS) window to be seen more because it only shows one row at a time. At the additional bottom right, you can add social media accounts, support email, help center, etc. This is only my suggestion as a trader, I hope you consider. Thank you!
![tomo](https://user-images.githubusercontent.com/58533399/72679165-81eef900-3ae7-11ea-9677-51ffdc904566.jpg)

**Comment by thanhvk** [comment]
duplicate https://github.com/tomochain/tomox-sdk-ui/issues/189

**Comment by thanhson1085** [comment]
He want to add socials link in the footer. but there are no exchange do that.
We do not consider this suggestion. thank you.
We will implement hompage for TomoDEX, then add social link there
