### ISSUE TITLE
Order History Informations Not Complete

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#47]
Good day! I have noticed something in the Dex via tomo wallet. Some informations in the Order History are missing (type, side, amount, total and status) that are very important because it is the history of all your orders. This will confuse a trader if his/her record is not complete.
![6278819A-EB2D-4548-98F4-7572CA0CA4D6](https://user-images.githubusercontent.com/58533399/72681608-36951480-3b00-11ea-84de-aafc72d65a92.png)

**Comment by thanhson1085** [comment]
We already add `amount` in this issue: https://github.com/tomochain/tomox-sdk-ui/issues/166
We do not consider to add more other fields.
