### ISSUE TITLE
Add period filter to Orders section

### ISSUE THREAD

**Issue by UmckaBear** [BuildOnViction/bug-reports#48]
I propose to add period display  filter for Orders section (Open Orders, Order History, Trade History) similar to picture below. You can select pre-sets like Today, Yesterday, 7 days, 30 days, etc or select required period manually. By default, it should show today's history.

![Improvement](https://user-images.githubusercontent.com/31537952/72682813-e905b100-3ad9-11ea-878b-12fb60be00e4.jpg)

**Comment by thanhson1085** [comment]
We do not consider this suggestion. thank you.
