### ISSUE TITLE
Reject order at high/low prices on the ALL pair

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#49]
when buy at a high price and sell low price
all pairs always reject, you can see this picture

![IMG_20200120_023410](https://user-images.githubusercontent.com/59077947/72687099-6e668100-3b2d-11ea-8278-d7c944fa1068.jpg)
![IMG_20200120_023425](https://user-images.githubusercontent.com/59077947/72687101-6eff1780-3b2d-11ea-9217-07f7ebdd5865.jpg)

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by thanhson1085** [comment]
It is NOT an issue.

If you create a order with amount <= 1 TOMO, the order will be rejected, because the amount is not enough to pay trade fee.
