### ISSUE TITLE
Error: After refresh, back to the default settings

### ISSUE THREAD

**Issue by AlexDCryptoC** [BuildOnViction/bug-reports#5]
Hi,

I set the timezone to Chicago and closed the wallet. I unlocked back the wallet and it went to default settings - UTC. (and not only the timezone)

Browser: Brave or Google Chrome

Tomo address: 0x7af113e499aa868fb200696983b237c0ac947f34
![tomo](https://user-images.githubusercontent.com/18679675/71181331-9b005200-227c-11ea-86a0-7db3a861686b.JPG)

**Comment by thanhson1085** [comment]
Thank you, but this is known issue https://github.com/tomochain/tomox-sdk-ui/issues/171
