### ISSUE TITLE
Notification moves!  not according to place

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#50]
See my video
https://streamable.com/91djc

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by thanhson1085** [comment]
Please test the product on the desktop, or TomoWallet Dapp browser

**Comment by 0xwhalerush** [comment]
Wait

**Comment by thanhson1085** [comment]
You have to use Desktop to test this issue. Feel free to reopen it if you can provide more information. Thank you.
