### ISSUE TITLE
Blank logo on Tomo Relayer

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#51]
I upload photos to online storage, then I paste link in Tomo Relayer the image cannot be loaded / blank

![IMG_20200120_032953](https://user-images.githubusercontent.com/59077947/72687923-2d726a80-3b35-11ea-8606-d7bc2c477ba0.jpg)

My logo Size 300x300
https://streamable.com/r9j7p

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by thanhson1085** [comment]
https://streamable.com/r9j7p -> it is NOT image link, you used a wrong link.

**Comment by 0xwhalerush** [comment]
Give me example link
