### ISSUE TITLE
Suggestion for 'CANCEL ALL' button for Open Orders

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#52]
I suggest there must be a 'Cancel All' button on Open Orders. For example if someone has put lot of orders but want to cancel it because the executed orders are unprofitable, of course it will take time for someone to cancel one by one and especially that prices are volatile, traders who want to adjust their orders will search for the 'Cancel All' button for faster cancellation and execution of new orders. 
![20200120_135801_compress96](https://user-images.githubusercontent.com/46350890/72702606-2c771400-3b08-11ea-9d1e-8e0ff3dde254.jpg)

**Comment by MirasolFerrer** [comment]
![20200120_135801_compress96](https://user-images.githubusercontent.com/46350890/72702535-e4f08800-3b07-11ea-9409-6d6968979551.jpg)

**Comment by CryptoChaser13** [comment]
Sorry i misclicked Close Issue, i hope i have successfully uploaded the picture

**Comment by thanhson1085** [comment]
We do NOT consider this suggestion

**Comment by CryptoChaser13** [comment]
Thats for traders sir. So they cancel all at once.

**Comment by CryptoChaser13** [comment]
Especially when they found a profitable trade when executed a lot of smaller trades at first.

**Comment by thanhson1085** [comment]
We understand. But this is decentralized exchange, not easy to implement that function.
