### ISSUE TITLE
Add “Operation” column in Funds section

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#53]
In the Dex via Tomowallet, it will be easier if you also put the operations in the funds section for more convenient trading.

TOMO Address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba

![2CDC383E-2C1A-45FD-AF34-3337406F1725](https://user-images.githubusercontent.com/58533399/72709054-05b7ec80-3b9f-11ea-972a-e2869ea57e03.png)

**Comment by thanhson1085** [comment]
We do not consider this suggestion
