### ISSUE TITLE
Blank logo on relayer

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#54]
logo cannot be open / blank

![IMG_20200120_155336](https://user-images.githubusercontent.com/59077947/72712171-15363600-3b9d-11ea-9420-a1cfdcbe1f06.jpg)

My logo 
https://drive.google.com/file/d/1-I4a8QZx7KrLWWDC7yCpzDzHPrMO1vWW/view

Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by 0xwhalerush** [comment]
![IMG_20200120_160638](https://user-images.githubusercontent.com/59077947/72713037-e1f4a680-3b9e-11ea-900e-24c5f17c0942.jpg)

**Comment by UmckaBear** [comment]
Hi @WhaleCMD 

I think, you didn't open public or URL access for file. You can see the result when I use your link.
![GoogleLogo](https://user-images.githubusercontent.com/31537952/72716617-3423d080-3b7b-11ea-9c99-0fbddfa89820.png)

**Comment by 0xwhalerush** [comment]
I set public same bro blank

**Comment by thanhson1085** [comment]
Wrong url. 

you have to use correct link. e.g: https://raw.githubusercontent.com/tomochain/logos/master/TomoX%404x.png
