### ISSUE TITLE
Last Price in USD under Market tab not Properly Aligned

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#56]
Good day! Im using cryptotab mobile browser with a full-web function. As I switch to the market tab, I noticed that the last price per US dollar is not properly aligned as you compare it to the other columns.  Some are almost close to others. Maybe you could label it too with "Last Price (USD)" to avoid misinterpretations.

![IMG_20200120_212104](https://user-images.githubusercontent.com/60099962/72730661-c1434580-3bcc-11ea-9550-559d4dcb9b18.jpg)

Fixing this issue will make this tab more pleasing to the eyes of the potential traders. Besides, this will gain an impression to viewers that the dex also cares for the user-friendly appearance aside from security.

![IMG_20200120_212101](https://user-images.githubusercontent.com/60099962/72730703-d15b2500-3bcc-11ea-9f63-f0e16cb47fe5.jpg)

Moreover, I also tried using google chrome browser  just  to confirm if it only happens in my cryptotab browser and I came out with the same result. Check my screenshots as a support. Thank you.

TOMO address: 0x4f2b8f23323cd74356227018bae28d560dd1b91a

**Comment by thanhson1085** [comment]
It is good padding with Last Price. it is not an issue

**Comment by SANJ33** [comment]
Oh I see. Thanks for confirmation. I will dig out more to find more issues. 🙂
