### ISSUE TITLE
Dex' Indicators are less recognizeable on desktop than on mobile app dex.

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#58]
Hello. Ive seen something in the dex' chart. As you can see on the first picture below, the price indication cant be recognizeable and its not easy to make analysis for this one. At first i presumed, maybe there are no orders at the 'can't be seen' indications on my desktop under BTC/TOMO pair until I have made a double check on my mobile app, now you can see the 2nd picture which i captured on my mobile app only to prove there were orders it can be recognizeable in the app and easy to make analysis for pricing. I have also tried to zoom in but i still cant recognize the indicators on desktop just like where did price pumped and dumped at a particular time. 
![tomo](https://user-images.githubusercontent.com/46350890/72810315-279e8700-3c12-11ea-9e01-412fb572cca2.png)

![Screenshot_20200121-213521_Tomo Wallet](https://user-images.githubusercontent.com/46350890/72810141-d2fb0c00-3c11-11ea-97ef-639b8b537ae7.jpg)

I suggest that just like the price indication on mobile app,  the price indicator on desktop must also be recognizeable in order for dex users to easily make analysis on pricing.

**Comment by thanhson1085** [comment]
It is not an issue. It is normal when the price change suddenly

**Comment by CryptoChaser13** [comment]
But on the desktop picture it is impossible to see when did price dumped or pumped, or at what value.

**Comment by CryptoChaser13** [comment]
Unlike in mobile app, the price indication is really clear and you can really see when and how much did price pumped or dumped.

**Comment by CryptoChaser13** [comment]
As you can see here, it would really become a hard time understanding this chart since we know lots of traders do their analysis and price predictions using this chart. 

![IMG_20200121_225521_717](https://user-images.githubusercontent.com/46350890/72815241-32a9e500-3c1b-11ea-9115-70000aeb5674.jpg)

**Comment by thanhson1085** [comment]
You can zoom the chart

**Comment by thanhson1085** [comment]
The chart shows the data correctly, no issue here

**Comment by CryptoChaser13** [comment]
Can i make send a video for doing the zoom in sir?

**Comment by thanhson1085** [comment]
I understand the description. But there is no issue here. 

You can try to change candle size to 1h, 1 day, you will understand. thank you
