### ISSUE TITLE
Chart Link Appearing i Depth

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#59]
Is this normally in here "JS chart by amCharts"? When i click it, it takes me to a site where the chart was made.
![tomo1](https://user-images.githubusercontent.com/58533399/72811092-e0f46f80-3c99-11ea-93c3-c5f171f60f3c.png)
![tomo2](https://user-images.githubusercontent.com/58533399/72811273-40eb1600-3c9a-11ea-8dd6-69c036f6bc6c.png)

**Comment by thanhson1085** [comment]
It is not an issue. We use tradingview for Candle chart and amchart for depth chart
