### ISSUE TITLE
Delay on cancel order and are not consistent with trading pairs

### ISSUE THREAD

**Issue by intan167** [BuildOnViction/bug-reports#6]
Login using private key
- Cancel order execution has a 1-2 second delay in certain pairs. in real situations it might be a little inconvenient if the user has a device that has a low specification
- Tomo's price is not consistent in some trade pairs, so it's easy for me to get profit, with 60 tomo from https://faucet.testnet.tomochain.com/ 
now my portfolio has increased significantly. 
![Screenshot_2019-12-20-10-30-31-730_com opera browser](https://user-images.githubusercontent.com/54311290/71229228-5249a700-2317-11ea-9d88-1d2fbe018f38.png)
Wallet addres: 
0x2bbB637bF5a349834d11E4c03E2BE7192E91E0a2

**Comment by thanhson1085** [comment]
Please show the detail info your device, browser and steps you did to create the issue

**Comment by thanhson1085** [comment]
Can you give me the address you used for the test?

**Comment by intan167** [comment]
> Please show the detail info your device, browser and steps you did to create the issue



> Can you give me the address you used for the test?

0x2bbB637bF5a349834d11E4c03E2BE7192E91E0a2
https://scan.testnet.tomochain.com/address/0x2bbB637bF5a349834d11E4c03E2BE7192E91E0a2
![Screenshot_2019-12-20-14-51-56-310_com opera browser](https://user-images.githubusercontent.com/54311290/71239597-859d2d80-2339-11ea-9e72-45584753b4c0.png)

**Comment by intan167** [comment]
> Please show the detail info your device, browser and steps you did to create the issue

Using Android OS 8.1.0 with chrome browser, opera crypto wallet and  Tomo dapp wallet, all log in via private key.  only on chrome runs quite smoothly

**Comment by thanhson1085** [comment]
Thank you for the report.

> Cancel order execution has a 1-2 second delay in certain pairs. in real situations it might be a little inconvenient if the user has a device that has a low specification

This is a know issue, team fixed it before you create the issue: https://github.com/tomochain/tomox-sdk/issues/106

> Tomo's price is not consistent in some trade pairs, so it's easy for me to get profit, with 60 tomo

It is trading bot issue, out of scope.
