### ISSUE TITLE
Web Server Nginx Outdated need to update

### ISSUE THREAD

**Issue by tramyargabam** [BuildOnViction/bug-reports#60]
I've scan the dex testnet website, It's appeared that the Nginx version of the web server is outdated (v.1.10.3) and its required to update to the lastest version to make it more secured especially for main net launch.

For more info about the vulnerabilities of Nginx version 1.10.3 check it out here : https://www.cvedetails.com/vulnerability-list/vendor_id-10048/product_id-17956/version_id-299575/Nginx-Nginx-1.10.3.html

Tomo Wallet Address : 0x0f43b05efe3cfd7c5bc3402cb05b4dfea5ab14b0

**Comment by thanhson1085** [comment]
It is not an issue if you can not propose a way to attack the web server.
