### ISSUE TITLE
No notification button on Dapp Dex

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#61]
I have noticed there is no any notification button for dex on mobile app unlike on browser. I cannot find any button to check for notifications as to whenever my order is already executed or been cancelled. Thank you.

**Comment by CryptoChaser13** [comment]
Im sure some users will get to know how are they going to get notified when their order's status.

**Comment by thanhson1085** [comment]
We do NOT accept this suggestion.
In the phase 2, the bounty is only for reporting bugs.
