### ISSUE TITLE
Different Transaction fees and Other Issues Encountered in Tomo wallet

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#63]
I'm using the latest version of Tomo wallet (V.0.10.2). My plan is to use the TomoDex in the testnet network. But first I decided to get 150 testnet TOMO in the testnet faucet that I can use to trade in the dex later on.
![Screenshot_20200121-224436](https://user-images.githubusercontent.com/60099962/72819339-0a1bfc80-3ca8-11ea-826e-0c66159a08dd.png)
And here's the unexpected part. Since I made two wallets just to test how fast the   TOMO be delivered to another wallet, I tried to send 150 TOMO to the 2nd wallet.Please see the  [link](https://dropmb.com/download/49652963f716706f0527b13f1d5d3006.html)  of my screen record while Im doing it live in Tomo wallet. What I've noticed is the max quantity that I can able to send to the other wallet.  For me, it should be my total TOMO less the transaction fees that I will incur. Another one is the "LEARN MORE" just below the expected transaction fee to be incurred. I am expecting that it has an embedded link/window showing on how the transaction fees are computed for every transactions made but nothing happened when i tried to click it.
![Screenshot_20200121-222640](https://user-images.githubusercontent.com/60099962/72819421-30419c80-3ca8-11ea-973a-5798f127b493.png)
Lastly is the transaction history of what I have made. As you can see, transaction fee recorded is only 0.000006 TOMO as compared to 0.000015 before I sent to the other wallet. Even the total received TOMO  by the other wallet is in question for me since it is still 150. So it means  no transactions fee actually deducted? Unless it is already rounded off without decimals.
![Screenshot_20200121-222715](https://user-images.githubusercontent.com/60099962/72819560-726ade00-3ca8-11ea-8350-3e9c469c6ad9.png)

Are those issues I have encountered be regarded as bugs or any explanations to what is  really happening to those I have mentioned?

**Comment by thanhson1085** [comment]
It is not an issue. 
TomoWallet estimate the fee, not exact fee.
The node will calculate the fee an execute the transaction.

It is also out of scope.
The bounty is only for TomoDEX, TomRelayer. Thank you.
