### ISSUE TITLE
Suggestions to add Market order and Stop-limit Order Options in TomoDEX

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#64]
![Screenshot_20200122-001900](https://user-images.githubusercontent.com/60099962/72822677-76e5c580-3cad-11ea-9bf9-3aecbf0333e0.png)
Good day🙂. I have noticed that the only available way to execute buy/sell orders is the LIMIT ORDER. I am suggesting to add MARKET ORDER as it is the best option for the trader if he/she wants to fill his/her orders in an instant. Another one is the STOP-LIMIT ORDER as it more convenient for the traders. For example, they can secure their profits by using this order type or they can minimize their losses. Im sure that more potentials traders will use the dex if this two will be added too.

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/bug-reports/issues/13
In phase 2 of the program, we only accept reporting bug.
