### ISSUE TITLE
Notifications  in Main Tomochain Network of Tomo wallet not Working

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#65]
![Screenshot_20200122-004828](https://user-images.githubusercontent.com/60099962/72824859-f7f28c00-3cb0-11ea-879c-abbd8864b1f4.png)
Tomowallet appearing this error after accessing the notification of main tomochain network. Im using Samsung Galaxy J2 Prime. See my video [link](https://dropmb.com/download/9d4bfc39cb496a9cc683a73cb3159575.html)  for  more documentation.
Version of Tomo wallet app: V.0.10.2

**Comment by thanhson1085** [comment]
This report is out of scope.
And duplicated https://github.com/tomochain/bug-reports/issues/55
