### ISSUE TITLE
Server Error Placing Order 2:19:00 UTC time 01/22/2020

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#66]
I cannot place buy or sell order exchange is down?

![serverrr](https://user-images.githubusercontent.com/38444647/72860107-d3260500-3d00-11ea-9729-c065c48271f1.png)

YT : https://www.youtube.com/watch?v=7Ht6dMGDRuM

**Comment by thanhson1085** [comment]
TomoChain is down at that time.
