### ISSUE TITLE
Undefined command when unlocking wallet on dex

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#67]
Hello. I tried to open the dex on my tomowallet. So i go now to my testnet account and clicked on dex. So now i can see everything is normal except for the buttons below Buy and Sell where i still need to unlock my wallet. But as i try to unlock it using mnemonic phrase, the following bug commands popped-out. Hope you fix this one. 

![Screenshot_20200122-103504_Tomo Wallet](https://user-images.githubusercontent.com/46350890/72861049-9b29ae00-3c7d-11ea-968a-19579b7cc9f7.jpg)
![Screenshot_20200122-103517_Tomo Wallet](https://user-images.githubusercontent.com/46350890/72861059-a1b82580-3c7d-11ea-876e-1a8ef1d80278.jpg)

I also made a video to prove my experience and will just paste the link below this issue.

**Comment by CryptoChaser13** [comment]
Here is the video

https://youtu.be/ACS1X2Ig51k

**Comment by thanhson1085** [comment]
TomoChain is down at that time. So TomoWallet can not unlock the wallet at that time.
