### ISSUE TITLE
There's no validation for minimum amount to transfer  tomo

### ISSUE THREAD

**Issue by zillabytes** [BuildOnViction/bug-reports#68]
I can send very little amount of tomo !!!
images successful transaction
![tomomany](https://user-images.githubusercontent.com/38444647/72870888-573db400-3d24-11ea-81bb-ac3bf495f1e8.png)

YT link : https://www.youtube.com/watch?v=0bHvAOfBgdg

**Comment by thanhson1085** [comment]
TomoChain network accepts to send with 0 balance. Do not need validate here.
