### ISSUE TITLE
Bug between Gas Settings and Receipt

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#69]
I have submitted a bug earlier about gas settings where the required gas can be manipulated as you change it on gas settings. 

At this time, i found out a bug between the gas settings and receipt. I am trying to send 1 tomo to another address. I know the required gas would be 21000. Yet i assumed to be more safe and more successful transaction so i adjusted the gas up to 21600. I have clicked the send button since transaction is valid. As expected it was successfully sent to the recipient. But as i show the receipt, the gas used there is still 21000, yet at first i used 21600. I also tried doing it in another transaction but i think what is shown in receipt is a fixed amount of gas which is 21000. I expect what is being input on the gas settings must be the gas shown on the receipt. 

![buuugs](https://user-images.githubusercontent.com/46350890/72876262-f32ad980-3caa-11ea-9371-336e657a3dbf.png)

This video will prove what i encountered:
https://youtu.be/BvfbmC1jakc

**Comment by thanhvk** [comment]
Gas settings to set gas limit and gas price not is gas use.
Some information in **Send tokens** popup not clear.
It will be solved in issue https://github.com/tomochain/bug-reports/issues/39. When I enhancement **Send tokens** popup.

**Comment by thanhson1085** [comment]
Gas Limit is different Gas Used, it is normal.
We do not consider it as an issue.
