### ISSUE TITLE
Cannot see 'Hide Other Pairs' button when in light mode

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#71]
Hello. I just want to submit the issue regarding the 'hide other pairs' button. On dark mode it can be easily seen. 
Here is my tomo address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

![456](https://user-images.githubusercontent.com/46350890/72881778-45bdc300-3cb6-11ea-85da-d42957e3deca.png)

But as i switched to light mode, its hard to see the button anymore:
![123](https://user-images.githubusercontent.com/46350890/72881822-5b32ed00-3cb6-11ea-9a66-ddf244abb801.png)

**Comment by CryptoChaser13** [comment]
Here is my tomo wallet:

0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
We did not consider it as an issue.
The checkbox is OK for us, you can click on the text.

**Comment by CryptoChaser13** [comment]
I think you need to change still the button as dark duting light mode so it has its purpose there, which is to be clicked upon and rather not click the words beside it.

**Comment by thanhson1085** [comment]
I understand your report. But it is too small to be consider at this phase

**Comment by CryptoChaser13** [comment]
Its okay sir. Thank you for verifying.
