### ISSUE TITLE
Another Bug in Light Mode

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#73]
I guess there are multiple bugs in light mode. Another one is the color of the boxes at the left side of the page when you point the cursor in it (Market, Exchange, Portfolio and Docs/FAQ).
My TOMO address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba
![tomo](https://user-images.githubusercontent.com/58533399/72893674-94219f00-3d54-11ea-9f98-dd5a1648752b.png)

**Comment by thanhson1085** [comment]
The tooltip color is OK in light mode. We do not consider it as an issue.
