### ISSUE TITLE
No 'Chart Properties' and 'Fullscreen Mode' on Dapp's DEX

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#74]
I figured out something in using our dapp's dex. Unlike at web, there is no 'Chart Properties' and even 'Fullscreen mode' on dapp's dex. 

Here is my tomo address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

Here are the pictures that we can compare:
![456](https://user-images.githubusercontent.com/46350890/72897846-b88b6600-3cd7-11ea-9268-2419927add1b.png)

![20200122_212106](https://user-images.githubusercontent.com/46350890/72897815-ac070d80-3cd7-11ea-8f42-75522d415694.jpg)

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/bug-reports/issues/10
