### ISSUE TITLE
Light Mode Bugs

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#75]
I noticed some bugs which are not yet mentioned on light mode issues. You can see the following dark pop-ups during light mode when cursor is moved unto it. '1m' , 'Candles', 'Indicators' , 'Chart Properties' , 'Fullscreen mode' . In addition, when i go through fullscreen mode, still light mode, the 'HIDE' pop-up is also at dark background. 

Here is my tomo address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

![1](https://user-images.githubusercontent.com/46350890/72900412-ad870480-3cdc-11ea-93c3-f3a7bc407e10.png)
![2](https://user-images.githubusercontent.com/46350890/72900436-b5df3f80-3cdc-11ea-862c-56b8cb19c700.png)

**Comment by CryptoChaser13** [comment]
Let me add these issues under this bug, all buttons below the chart are on dark color when in light mode and cursor is positioned unto them 'Timezone', '%', 'log', 'auto' and 'chart properties'. 

![bbbbbbbbbbbbb](https://user-images.githubusercontent.com/46350890/72962356-f84e5e00-3d68-11ea-8a7a-0d5efcc0fb96.png)

**Comment by thanhson1085** [comment]
The tooltip color is OK in light mode. We do not consider it as an issue.
