### ISSUE TITLE
Unclear button of 'Hide Zero Amounts' on Portfolio during light mode

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#78]
I noticed another unclear button when switching to light view, please verfy through the following screenshots:
Here is my tomo address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

![b](https://user-images.githubusercontent.com/46350890/72948666-b4446480-3d3a-11ea-8059-e6dde90bbeb1.png)
![a](https://user-images.githubusercontent.com/46350890/72948675-b9a1af00-3d3a-11ea-9573-2c8485aa6f7f.png)

**Comment by thanhson1085** [comment]
The checkbox color is OK for light mode, you also can click on the text. we do not consider it as an issue.
