### ISSUE TITLE
Decide One Color For Icons

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#79]
Is it possible that you make only one color for the icons when you place the cursor on it? When I place it on the "send", "receive", coin names and operations, the color will be orange but when I place the cursor on the icons at the top right and left column, it turns white and in light mode, it turns gray.
My TOMO address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba
![TOMO](https://user-images.githubusercontent.com/58533399/72948923-b271b400-3dc1-11ea-9b96-20a32714ecce.png)
![TOMO1](https://user-images.githubusercontent.com/58533399/72948925-b30a4a80-3dc1-11ea-83a7-cebf5886c128.png)
![TOMO2](https://user-images.githubusercontent.com/58533399/72948926-b30a4a80-3dc1-11ea-87a2-3a4850a460d6.png)

**Comment by thanhson1085** [comment]
Thank you for the suggestion. But it is too minor to be considered as an issue.
