### ISSUE TITLE
No display of tokens after purchase

### ISSUE THREAD

**Issue by DooY00doO** [BuildOnViction/bug-reports#8]
When buying tokens from TomoDex via TomoWallet, these tokens do not appear in the wallet on the main page. It's not a big problem but, on the one hand, I don't know if this is normal and, on the other hand, it's not very "user friendly".

Purchases made :
![Screenshot_20191220-092844_Tomo Wallet](https://user-images.githubusercontent.com/59082778/71242203-c1220280-230d-11ea-99ca-ac1f2a67c258.jpg)

They do not appear on the home page.
![Screenshot_20191220-092901_Tomo Wallet](https://user-images.githubusercontent.com/59082778/71242234-d1d27880-230d-11ea-89e2-025e26cb8869.jpg)

Tomo adress : 0xd76105b11ad56f8e6a4f756611ed7aad54a82f83

**Comment by thanhson1085** [comment]
You will see the token when click "manage".
It is out of scope issue.
Thank you.
