### ISSUE TITLE
There is No Meta Description in Website

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#80]
I did some auditing of the website, and in the SEO, there's an issue that appeared. There is no Meta Description. I think this is important to direct more traffic to the website.
My TOMO address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba
![tomo3](https://user-images.githubusercontent.com/58533399/72952451-dd153a00-3dcc-11ea-9733-f3ba6a793938.png)

**Comment by thanhson1085** [comment]
SEO friendly is important for TomoChain website. But TomoDEX is a web application for trading, no news or blog post, So we do not consider it as an issue at this phase.
