### ISSUE TITLE
Different chart again but now for LTC/TOMO Pair

### ISSUE THREAD

**Issue by gsarahhhh** [BuildOnViction/bug-reports#81]
I just noticed when I browse the other charts it shows the volume even if it is buying or selling you can easily see how huge the pump or dump because of the candles but when I chose the LTC/TOMO pair I cannot clearly see the volume candle

![image](https://user-images.githubusercontent.com/59993482/72954742-5ebc9600-3dd4-11ea-8a76-3dfe8e35b467.png)

**Comment by thanhson1085** [comment]
Duplicated https://github.com/tomochain/bug-reports/issues/77
