### ISSUE TITLE
Zooming in Disabled

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#82]
I've run an audit with accessibility and it turns out that zooming is disabled. 
[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5. Zooming is quite important to those who have low vision who relies on zooming the screen to properly see the contents of the web page.
My TOMO address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba
![tomo4](https://user-images.githubusercontent.com/58533399/72957328-1dc97f00-3dde-11ea-9c42-f9bf2c612455.png)

**Comment by thanhson1085** [comment]
We do NOT want to enable zoom, so it can show consistent on the device.

**Comment by thanhson1085** [comment]
Thank you for the suggestion. You should know that the bounty is only for bug report.
