### ISSUE TITLE
Redundant Timezone

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#84]
While trying to select timezones, ive noticed that there are two  which has the same timezone, the 'UTC' and 'Exchange'. I am expecting yhese two mustbe combined such as 'UTC/EXCHANGE' since they have the same timezone. 
Here is my tomo address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

![aaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/46350890/72961543-431aa680-3d66-11ea-9b64-f0c2554f9642.png)
https://youtu.be/D4IV9mHuGZc

**Comment by thanhvk** [comment]
Thanks but we don't see this as an issue.

**Comment by CryptoChaser13** [comment]
Thank you sir. But may i ask , is it okay my enhancement label was removed here? 👇

https://github.com/tomochain/bug-reports/issues/71#issue-553412595
