### ISSUE TITLE
Desired Decimal Window in TomoDEX 

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#85]
I think its better if you lock scrolling while this window is still open
![Screenshot_20200123-174438](https://user-images.githubusercontent.com/60099962/72973408-2a62cd00-3e08-11ea-907e-e479e5b4d61f.png)

Video link: https://youtu.be/TdBDa714dnQ

**Comment by SANJ33** [comment]
Btw, that's my first proposal. My second proposal is to still enable the scrolling mode but this window will have a fixed position as shown in the picture(e.g. scrolled up when you scrolled up too or scrolled down when  you scrolled it down too.)
![Screenshot_20200123-200026](https://user-images.githubusercontent.com/60099962/72983128-9a2e8300-3e1b-11ea-82ee-57f9fc75c6c3.png)

**Comment by thanhson1085** [comment]
I do not think that we need to look the box. It should follow the scroll, then user can select the options. 
Thank you for the report. We do NOT consider it an issue.
