### ISSUE TITLE
Sudden Sorting of the Sell Orderbook after Choosing Desired Level of Decimal to Show

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#86]
As I exploring the TomoDex using Tomo wallet, I have noticed that after choosing desired decimal to show, the sell orderbook is sorted from top to bottom for about 1-2 seconds and then goes back to their current position. Buy orderbook seems working fine and only the sell orderbook have this issue.
https://youtu.be/m5c-IU4ewjc

**Comment by SANJ33** [comment]
Sudden sorting also happening in the web

**Comment by UmckaBear** [comment]
This is duplication of https://github.com/tomochain/bug-reports/issues/24 report

**Comment by thanhvk** [comment]
Thanks, @UmckaBear & @SANJ33
