### ISSUE TITLE
Bug if You Buy at a Price Higher than in the Sell Book

### ISSUE THREAD

**Issue by SANJ33** [BuildOnViction/bug-reports#87]
https://youtu.be/JgA02jgJXyo

Im on the ADA/TOMO  pair having 80 available TOMO for trading.The price listed in the  sell book order is ranging from  0.11731-0.11848 but I set the price at 0.19 in exchange for 420.6315789 ADA with remaining balance of 0.08 TOMO after it was executed. But when I made   another buy order with 100%( supposedly not possible), I still have remaining balance to accumulate more ADA token. As a result I have accumulated 674 ADA in total wherein if you averaged the price, I only bought them at 0.118575 . Is it possible to make a code wherein buyers can only make a valid buy order if the price is lower than the sell book (e.g BUY LIMIT ORDER) and within the sellbook with the highest selling price placed will be the maximum buy price for the buyers? As this one will prevent the bug.

**Comment by thanhson1085** [comment]
It is not an issue.

You can buy ADA with price 0.19. The matching engine will find the best price in orderbook to match your orders. And you can see the best price for your order is 0.11, then you can buy ADA cheaper.
