### ISSUE TITLE
Bug on Unlocking Wallet (January 24, 2020, 6:55 AM Philippine Standard Time)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#89]
Hello. Same issue which has happened lat few days happened again today January 24, 2020 at 6:55 am Philippine Standard Time. As i tried to unlock wallet on dapp' dex, i can see this unknown pop-up. Kindly verify what happened here. Thank you. 

![Screenshot_20200124-065942_Tomo Wallet](https://user-images.githubusercontent.com/46350890/73031667-a0a80500-3df1-11ea-8336-f5e0de225b8f.jpg)

Ill upload the video of this encounter and will just follow up the link below this issue later.

**Comment by CryptoChaser13** [comment]
https://youtu.be/baz1qYaMsKk

**Comment by thanhson1085** [comment]
Thank you for the report. You can not access the site, because TomoChain testnet is down at that time.
