### ISSUE TITLE
Cryptocurrency Pairs Does Not Show in Landscape Mode

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#9]
In homepage, I can normally see the crypto pairs but when I’ve activated the landscape mode on my phone, the pairs seems to disappear. I’m using an iPhone 6, Google Chrome browser.
![709BDAA8-5660-46EE-A00D-34C6E58359A6](https://user-images.githubusercontent.com/58533399/71594275-414c3180-2b72-11ea-818d-1773b1f53abb.png)
![4BF02B9F-75F0-4972-A81F-F55744CFFC29](https://user-images.githubusercontent.com/58533399/71594278-43ae8b80-2b72-11ea-90eb-2772725c7a9b.png)

My TOMO address: 0x22dB471611D3e6fDA30104f39d5E42d710ef1fE8

**Comment by thanhson1085** [comment]
Thank you for the report, but it is out of scope. Please use TomoWallet, testnet mode, then go TomoDex Dapp.

https://github.com/tomochain/bug-reports#out-of-scope
