### ISSUE TITLE
Dex Can't Also Load in Brave Browser

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#90]
I've also tried opening the Dex in Brave Browser, but it does not load. We know that Brave Browser has a big number of users and it is also related in crypto.
My TOMO address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba
![tomoo2](https://user-images.githubusercontent.com/58533399/73036720-6c7f2380-3e87-11ea-8be6-4aa7c39fb341.png)

**Comment by UmckaBear** [comment]
Brave browser - no issues. All works as expected even with turned on Brave Shield
Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

![Brave](https://user-images.githubusercontent.com/31537952/73043590-819b8880-3e6e-11ea-8003-70e413bd4b55.jpg)

**Comment by thanhvk** [comment]
It works well on Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit) too.
Thanks, @UmckaBear  & @RonaldDuck.
