### ISSUE TITLE
Descending Arrangement of Pairs when opening in other browser (Mozilla Firefox)

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#93]
Hello. I just noticed another issue about the arrangement of pairs in the dexchange.
When opened in google chrome, these are the (i think original) arrangements of the pairs which is in ascending (A,B,C and so on) order:
![arran](https://user-images.githubusercontent.com/46350890/73059579-f99a9a80-3ed0-11ea-9c7a-3eb9b421dbd7.png)
![arran a](https://user-images.githubusercontent.com/46350890/73059581-fa333100-3ed0-11ea-9a9d-ea0277b03479.png)
Whereas when tried to open in Mozilla Firefox, the arrangement is different, it's already in descending order both Tomo and BTC Pairs:
![ababa](https://user-images.githubusercontent.com/46350890/73059876-a117cd00-3ed1-11ea-8c67-572555174bca.png)
![arrange 2](https://user-images.githubusercontent.com/46350890/73059640-22bb2b00-3ed1-11ea-94bb-082ed7afd11a.png)

Here is my tomo wallet:

0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
It is too minor to be considered as an issue at this time. thank you.
