### ISSUE TITLE
Cannot show full command when try to long press middle part of chart

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#95]
Hello. I just tried to long press the chart and found out that there is a command upon doing it. I tried it first on the right part of the chart and this picture shows:
![Screenshot_20200126-005418_Tomo Wallet](https://user-images.githubusercontent.com/46350890/73124457-aa944a00-3f50-11ea-9344-e34436211452.jpg)
Afterwards i also tried it on the left part of the chart and this shows:
![Screenshot_20200126-005458_Tomo Wallet](https://user-images.githubusercontent.com/46350890/73124484-d9122500-3f50-11ea-887f-b4fe821a9f6f.jpg)
But as i long pressed at the middle part, then this is shown:
![Screenshot_20200126-005408_Tomo Wallet](https://user-images.githubusercontent.com/46350890/73124500-ea5b3180-3f50-11ea-9069-294cb2f0cb6d.jpg)
And it cant even move now and the main option would be just to click outside the command to make it disappear. 

Here is my tomo wallet:

0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by thanhson1085** [comment]
It is too small to be consider it as an issue.
Thank you.
