### ISSUE TITLE
Current Price Cannot Be Selected For Buy and Sell

### ISSUE THREAD

**Issue by RonaldDuck** [BuildOnViction/bug-reports#96]
All the prices in the orderbook can be selected for buy and sell except the current price. Also, the last price you selected (except the current price) even when you tap another area other than the orderbook will be the price that appears on the buy and sell page.
My TOMO address: 0xa57b0f005085a1f81b2834c84de9c917e32352ba

![335700BC-D421-4374-9E24-F3055F1AA8A2](https://user-images.githubusercontent.com/58533399/73128205-dd991500-4006-11ea-8747-4b7ce9dd1201.jpeg)
![A1C243F2-2E0E-483B-9377-DFE044B4E004](https://user-images.githubusercontent.com/58533399/73128206-dd991500-4006-11ea-82c0-79beecd07d15.jpeg)
![D0E2F438-606E-4ED9-AEC1-9427634AD1A9](https://user-images.githubusercontent.com/58533399/73128207-de31ab80-4006-11ea-97a2-d31377c88ffd.jpeg)

**Comment by thanhson1085** [comment]
We do not think the text should be clickable. Thank you for the suggestion
