### ISSUE TITLE
Open Orders are reduced when try to reload the dex

### ISSUE THREAD

**Issue by CryptoChaser13** [BuildOnViction/bug-reports#98]
Hello. I tried to execute buy orders using very small price than those on orderbook. I tried to make 55 buy orders and have successfully submitted all of it. As per checking also on my notification, all orders are submitted and none are executed yet or closed. So here is the first picture:
![1111111111111111111111111111111111111111](https://user-images.githubusercontent.com/46350890/73131009-6da68100-403e-11ea-9f4b-5f033b4a1349.png)
Then i tried to reload the website, but suddenly this is what ive seen, The orders are reduced to 46 only. Yet i can also see my latest order still in it. I have also checked on notification if there were executed or closed orders, but the latest message was the successful order submission:
![2222222222222222222](https://user-images.githubusercontent.com/46350890/73131019-a6def100-403e-11ea-9306-3c6a8e4ab2c9.png)
You can also check my encounter here:
https://youtu.be/S0kx2wLjFFc

Here is my Tomo wallet address:
0xafb82d9c2609ead9534774b16f9d1377d2decea3

**Comment by UmckaBear** [comment]
I have already opened ticket https://github.com/tomochain/bug-reports/issues/33 for this issue. It is more deeper than you can see on first sigh. There linked limit for "Open Orders" and "Order history" = max 50 showed items after refresh. All these were already described.

**Comment by CryptoChaser13** [comment]
Hello @UmckaBear just as i have ecountered the issue, i have checked the submissions even yours but i think your issue is a bit complicated, so i submitted it separately which is at my side, easier to reproduce.

**Comment by UmckaBear** [comment]
@MirasolFerrer to reproduce it you need open 50+ orders, so what is the difference and difficult with my reproducing? Same description, same reproducing and same issue. 

PS Team spend more time on checking and closing double, triple reported duplicates.

**Comment by CryptoChaser13** [comment]
Yet i think it wasn't reproduced yet by the team. Thanks still for a follow-up.

**Comment by thanhson1085** [comment]
Thank you for the report. but it is a duplicated issue https://github.com/tomochain/bug-reports/issues/33
